'use strict';
const main=document.getElementById('main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=null,me=null,course=null,renderId=0;
try{session=JSON.parse(sessionStorage.getItem('tuberculum-session'));}catch{}
function keepSession(s){session=s;if(s)sessionStorage.setItem('tuberculum-session',JSON.stringify(s));else sessionStorage.removeItem('tuberculum-session');}
async function auth(path,data){const r=await fetch(AUTH_URL+path,{method:'POST',headers:{apikey:PUBLIC_KEY,'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||'Unable to sign in.');return d;}
async function api(action,data={}){
 if(session&&session.expires_at*1000<Date.now()+30000){try{keepSession(await auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token}));}catch{keepSession(null);throw Error('Please sign in again.');}}
 const r=await fetch(COURSE_API,{method:'POST',headers:{apikey:PUBLIC_KEY,'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify({action,...data})});const d=await r.json();if(!r.ok){if(r.status===401)keepSession(null);throw Error(d.error||'Unable to save. Please try again.');}return d;
}
function error(e){let box=document.getElementById('error');if(!box){box=document.createElement('p');box.id='error';box.className='notice error';box.setAttribute('role','alert');main.prepend(box);}box.textContent=e.message||e;}
async function busy(form,fn){const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){error(e);}finally{if(form.dataset.locked!=='true')buttons.forEach(b=>b.disabled=false);}}
function navigate(hash){if(location.hash==='#'+hash)render();else location.hash=hash;}
const btn=(label,hash)=>`<a class="btn secondary" href="#${hash}">${label} →</a>`;
function nav(){document.getElementById('nav').innerHTML=me?`${me.role==='admin'?'<a href="#admin">Administrator</a>':''}<a href="#home">Home</a><a href="#learn">Course</a><a href="#exam">Final assessment</a><a href="#reference">Clinical references</a><a href="#account">My account</a><button class="text-btn" id="signout">Sign out</button>`:'';document.getElementById('account-status').textContent=me?me.email:'';const b=document.getElementById('signout');if(b)b.onclick=async()=>{if(session)await fetch(AUTH_URL+'logout',{method:'POST',headers:{apikey:PUBLIC_KEY,Authorization:'Bearer '+session.access_token}}).catch(()=>{});keepSession(null);me=null;course=null;navigate('signin');};}
function signin(){main.innerHTML=`<div class="eyebrow">WELCOME TO TUBERCULUM</div><h1>Return to your learning.</h1><p class="intro">Sign in to continue your patient journeys and keep your course record across devices.</p><form id="login" class="fields"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="btn">Sign in →</button></form><p>New to Tuberculum? <a href="#signup">Create an account</a> to begin.</p><details><summary>Forgotten your password?</summary><p>Ask the course administrator at <a href="mailto:tuberculum.course@gmail.com">tuberculum.course@gmail.com</a> for a personal recovery link. It lets you set a new password.</p></details>`;main.insertAdjacentHTML('beforeend','<details><summary>How to use Tuberculum</summary>'+howToUse().replace('<h2>How to use Tuberculum</h2>','')+'</details>');document.getElementById('login').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{const d=new FormData(e.target);keepSession(await auth('token?grant_type=password',{email:d.get('email'),password:d.get('password')}));me=null;navigate('home');});};}

function signup(){main.innerHTML=`<div class="eyebrow">WELCOME TO TUBERCULUM</div><h1>Begin your learning.</h1><p class="intro">Create your learner account. No invitation is needed.</p><form id="signup" class="fields"><label>Email<input type="email" name="email" autocomplete="username" maxlength="254" required></label><label>Password<input type="password" name="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><label>Confirm password<input type="password" name="confirm" minlength="12" maxlength="128" autocomplete="new-password" required></label><p>Use at least 12 characters. A phrase of several words works well.</p><p class="small">You will verify your email, then complete your learner profile, including your MCR number, postgraduate year and specialty. See <a href="#privacy">how your course records are used</a>.</p><button class="btn">Create account →</button></form><p>Already registered? <a href="#signin">Sign in</a>.</p>`;document.getElementById('signup').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{const f=new FormData(e.target);if(f.get('password')!==f.get('confirm'))throw Error('The passwords do not match.');const d=await auth('signup?redirect_to='+encodeURIComponent('https://tuberculum.vercel.app/'),{email:String(f.get('email')).trim(),password:f.get('password')});if(d.access_token){keepSession(d);me=null;navigate('home');return;}main.innerHTML=`<h1>Check your email.</h1><p>If registration can proceed, you will receive a confirmation email. Follow its verification link, then return here to sign in.</p><p>Already have an account? Sign in using your existing password.</p>${btn('Sign in','signin')}<p class="small">Check your spam folder. If the email does not arrive, contact <a href="mailto:tuberculum.course@gmail.com">tuberculum.course@gmail.com</a>.</p>`;});};}

function accept(token){main.innerHTML=`<div class="eyebrow">YOUR PERSONAL COURSE LINK</div><h1>Set your password.</h1><p>Create a password to activate your invitation or recover your existing account. This link can be used once.</p><form id="accept" class="fields"><label>New password<input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><label>Confirm password<input name="confirm" type="password" minlength="12" autocomplete="new-password" required></label><p>Use at least 12 characters. A phrase of several words works well.</p><button class="btn">Save password and continue →</button></form>`;document.getElementById('accept').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{const f=new FormData(e.target);if(f.get('password')!==f.get('confirm'))throw Error('The passwords do not match.');const d=await api('accept',{token,password:f.get('password')});history.replaceState(null,'','#signin');keepSession(await auth('token?grant_type=password',{email:d.email,password:f.get('password')}));me=null;navigate('home');});};}
const specialties=['Family Medicine / General Practice','Internal Medicine','Infectious Diseases','Respiratory Medicine','Emergency Medicine','Geriatric Medicine','Paediatrics','Obstetrics and Gynaecology','General Surgery','Orthopaedic Surgery','Anaesthesiology','Psychiatry','Radiology','Public Health','Occupational Medicine'];
function profile(embedded=false){const p=me.profile||{};const other=!!p.specialty&&!specialties.includes(p.specialty);main.innerHTML=`${embedded?'<h1>My account</h1><details><summary>Profile details</summary>':'<h1>Your learner profile</h1>'}<p>These details identify your learning record. Your name will appear on your completion certificate.</p><form id="profile" class="fields">${[['full_name','Full name'],['organisation','Organisation'],['mcr_number','MCR number']].map(([id,label])=>`<label>${label}<input name="${id}" maxlength="150" value="${esc(p[id])}" required></label>`).join('')}<label>Specialty<select name="specialty" id="specialty" required><option value="">Select your specialty</option>${specialties.map(s=>`<option value="${esc(s)}" ${p.specialty===s?'selected':''}>${esc(s)}</option>`).join('')}<option value="other" ${other?'selected':''}>Other — please specify</option></select></label><label id="other-specialty-label" ${other?'':'hidden'}>Please specify your specialty<input name="other_specialty" id="other-specialty" maxlength="150" value="${other?esc(p.specialty):''}" ${other?'required':'disabled'}></label><label>Postgraduate year<input name="postgraduate_year" type="number" min="1" max="80" value="${p.postgraduate_year||''}" required></label><p class="small">Your profile, responses, confidence ratings and progress are stored for course administration. See <a href="#privacy">how your records are used</a>. Do not enter patient information.</p><button class="btn">Save profile →</button></form>${embedded?'</details>':''}`;document.getElementById('specialty').onchange=e=>{const show=e.target.value==='other';document.getElementById('other-specialty-label').hidden=!show;const input=document.getElementById('other-specialty');input.disabled=!show;input.required=show;};document.getElementById('profile').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{const p=Object.fromEntries(new FormData(e.target));if(p.specialty==='other'){p.specialty=String(p.other_specialty||'').trim();if(!p.specialty)throw Error('Please specify your specialty.');}delete p.other_specialty;p.postgraduate_year=Number(p.postgraduate_year);me=await api('profile',{profile:p});navigate(embedded?'account':'home');});};}
function privacy(){main.innerHTML=`<div class="privacy"><h1>Your course records</h1><p>Tuberculum stores your name, email, organisation, MCR number, postgraduate year and specialty, together with your learning activity, assessment responses, scores, confidence ratings, feedback and certificate record.</p><p>Dr Tay Jun Yang is the responsible course owner. The course administrator can view and export these records to administer access, monitor completion and improve teaching. Records are stored in the course’s Supabase project. Vercel hosts the application.</p><p>Confidence ratings describe your own perception and are considered separately from knowledge scores. General feedback is optional. Do not enter real patient information.</p><p>For access, correction or deletion requests, contact <a href="mailto:tuberculum.course@gmail.com">tuberculum.course@gmail.com</a>.</p>${btn('Return to course','home')}</div>`;}
const confidenceLabels=['Not at all confident','Slightly confident','Moderately confident','Very confident','Extremely confident'];

function expansionCase(value,prefix){return /(?:^|[.!?]\s+)[\s“”"'‘’(]*$/.test(prefix)?value.charAt(0).toUpperCase()+value.slice(1):value;}
function assessmentWording(items,areas){
 const terms={BCG:'bacille Calmette–Guérin (BCG)',IGRA:'interferon-gamma release assay (IGRA)',NTBCC:'National Tuberculosis Care Centre (NTBCC)','4R':'four months of daily rifampicin (4R)',CXR:'chest radiograph (CXR)','6H':'six months of daily isoniazid (6H)',GP:'general practitioner (GP)',NTBSC:'National Tuberculosis Screening Centre (NTBSC)'};
 const seen=new Set();
 const expand=s=>s.replace(/\b(?:BCG|IGRA|NTBCC|4R|CXR|6H|GP|NTBSC)\b/g,(t,index,text)=>{if(seen.has(t))return t;seen.add(t);return expansionCase(terms[t],text.slice(0,index));});
 return {items:items.map(q=>({...q,stem:expand(q.stem),question:expand(q.question),options:q.options.map(expand)})),areas:areas.map(([id,label])=>[id,expand(label)])};
}
function evaluationForm(post=false){const wording=assessmentWording(me.anchors,me.confidenceAreas);main.innerHTML=`<div class="eyebrow">${post?'LEARNING REFLECTION':'CLINICAL WARM-UP'}</div><h1>${post?'Reflect on your learning.':'Start with a few clinical decisions.'}</h1><p class="intro">Allow 8–10 minutes. Choose “I am not sure” when needed. Confidence ratings begin at the middle value; you can leave them there.</p><form id="evaluation">${wording.items.map((q,i)=>`<section class="card" style="margin-bottom:20px"><span class="question-count">${i+1} / 10</span><p>${q.stem}</p><h3>${q.question}</h3><div class="options">${[...q.options,'I am not sure'].map((o,j)=>`<label class="option"><input required type="radio" name="${q.id}" value="${j}"><span>${esc(o)}</span></label>`).join('')}</div></section>`).join('')}<section class="card"><h2>Your confidence today</h2>${wording.areas.map(([id,label])=>`<fieldset class="confidence-rating"><legend>${label}</legend><input class="confidence-range" type="range" name="C-${id}" aria-label="${label}" min="1" max="5" value="3"><output>3 — Moderately confident</output><div class="confidence-anchors"><span>1 · Not at all</span><span>5 · Extremely</span></div></fieldset>`).join('')}</section>${post?'<section class="card"><h2>Help us improve the course</h2><label>What helped, and what could be improved? (Optional)<textarea name="feedback" rows="5" maxlength="4000"></textarea></label></section>':''}<div class="actions"><button class="btn">${post?'Save reflection':'Save and begin learning'} →</button></div></form>`;
 const form=document.getElementById('evaluation');form.querySelectorAll('[type=range]').forEach(el=>el.oninput=()=>el.nextElementSibling.textContent=el.value+' — '+confidenceLabels[el.value-1]);
 form.onsubmit=e=>{e.preventDefault();busy(form,async()=>{const f=new FormData(form);const answers=Object.fromEntries(me.anchors.map(q=>[q.id,Number(f.get(q.id))]));const confidence=Object.fromEntries(me.confidenceAreas.map(([id])=>[id,Number(f.get('C-'+id))]));me=await api(post?'reflection':'warmup',{answers,confidence,feedback:f.get('feedback')||''});navigate(post?'reflection-review':'home');});};}
function videoButton(i){const v=course.videos[i];return v?.youtubeId?`<button class="video-btn" data-video="${i}">▷ ${esc(v.title)}<span>${esc(v.duration)}</span></button>`:`<p class="small muted">Explainer video planned: ${esc(v?.title||'')}</p>`;}
function bindVideos(){document.querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>{const v=course.videos[Number(b.dataset.video)];if(!/^[\w-]{11}$/.test(v.youtubeId))return;document.getElementById('video-content').innerHTML=`<h2>${esc(v.title)}</h2><iframe style="width:100%;aspect-ratio:16/9;border:0" src="https://www.youtube-nocookie.com/embed/${v.youtubeId}?rel=0" title="${esc(v.title)}" allow="autoplay; encrypted-media; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`;document.getElementById('video').showModal();});}

const clinicalTerms={CDA:'Communicable Diseases Agency',CDC:'Centers for Disease Control and Prevention',CDLENS:'Communicable Diseases Live and Enhanced Surveillance',GPs:'general practitioners',IGRA:'interferon-gamma release assay',TST:'tuberculin skin test',BCG:'bacille Calmette–Guérin',CXR:'chest radiograph',AFB:'acid-fast bacilli',PCR:'polymerase chain reaction',ALT:'alanine aminotransferase',AST:'aspartate aminotransferase',ULN:'upper limit of normal',HIV:'human immunodeficiency virus',MDR:'multidrug-resistant',GP:'general practitioner',NTBSC:'National Tuberculosis Screening Centre',NTBCC:'National Tuberculosis Care Centre','4R':'four months of daily rifampicin','6H':'six months of daily isoniazid'};
function expandClinicalTerms(root=main){
 const scopes=new Map(),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 for(const node of nodes){if(node.parentElement.closest('svg,script,style,button,a,option,textarea'))continue;const scope=node.parentElement.closest('section,article,details,form,table')||root;if(!scopes.has(scope))scopes.set(scope,new Set());const seen=scopes.get(scope);const block=node.parentElement.closest('h1,h2,h3,h4,h5,h6,p,li,td,th,summary,label,legend,div')||scope;const range=document.createRange();range.selectNodeContents(block);range.setEnd(node,0);const preceding=range.toString();node.textContent=node.textContent.replace(/\b(?:CDA|CDC|CDLENS|GPs|IGRA|TST|BCG|CXR|AFB|PCR|ALT|AST|ULN|HIV|MDR|GP|NTBSC|NTBCC|4R|6H)\b/g,(term,index,text)=>{if(seen.has(term))return term;seen.add(term);const full=clinicalTerms[term];if((preceding+text.slice(0,index)).toLowerCase().endsWith(full.toLowerCase()+' ('))return term;return expansionCase(full,preceding+text.slice(0,index))+' ('+term+')';});}

}
function howToUse(){return `<section class="card"><h2>How to use Tuberculum</h2><ol><li><strong>Start with your profile and clinical warm-up.</strong> Complete your details, then make a few clinical decisions and rate your confidence. It is fine to select “I am not sure”.</li><li><strong>Learn, then apply.</strong> Follow each teaching experience with its patient journey. Use the short explanations, visuals and available videos; open deeper explanations when helpful.</li><li><strong>Commit, review and revisit.</strong> Submit your answer to see the reasoning. Return to the teaching whenever you need a refresher.</li><li><strong>Finish with the assessment and reflection.</strong> Complete the teaching and journeys, then take the untimed, open-reference final assessment. A score of 21/30 or above passes. If needed, complete targeted revision and try again.</li></ol><p>Allow approximately 3–4 hours, spread across short sessions. Submitted answers are saved across devices; unfinished selections are not saved. Find your profile, progress and certificate under <strong>My account</strong>. Your certificate becomes available after you complete the course requirements and closing reflection.</p></section>`;}

function home(){const s=me.record;main.innerHTML=`<div class="eyebrow">YOUR LEARNING PRACTICE</div><h1>From a result to a safe plan.</h1><p class="intro">Build the foundations. Practise the decisions. Return to your patients as their care unfolds.</p><section class="card"><h2>Welcome to Tuberculum</h2><p>Explore how the course connects TB knowledge with patient journeys, clinical decisions and feedback.</p>${videoButton(8)}</section>${howToUse()}<section class="next-learning"><div><h2>Your next step</h2><p>${Object.keys(s.lessons).length} / 9 teaching experiences · ${course.caseOrder.filter(id=>s.cases[id]?.length===course.cases[id].steps.length).length} / 9 patient journeys</p></div>${btn('Open learning pathway','learn')}</section><p class="save-state">Your submitted decisions are saved to your account.</p>`;bindVideos();}
function pathway(){const s=me.record;main.innerHTML=`<h1>Build understanding. Then use it.</h1><p class="intro">Nine teaching experiences and patient journeys prepare you for the final assessment. Allow approximately 3–4 hours, across short sessions.</p>${course.lessons.map((l,i)=>`<article class="lesson-row"><div><span class="eyebrow">${l.phase} · ${l.time} min</span><h2>${i+1}. ${l.title}</h2><p>${l.objective}</p><p>${s.lessons[l.id]?'✓ Teaching complete':'Teaching to do'} · ${s.cases[l.caseId]?.length===course.cases[l.caseId].steps.length?'✓ Patient journey complete':'Patient journey to do'}</p>${btn('Teaching','lesson/'+l.id)} ${btn(course.cases[l.caseId].name+'’s journey','case/'+l.caseId)}</div></article>`).join('')}<div class="actions">${btn('Final assessment','exam')}</div>`;}
const answerOutcome=points=>points===1?'Correct':points>0?'Partially correct':'Incorrect';
function answerReview(q,selected,answer=q.answer){
 const expected=Array.isArray(answer)?answer:[answer];
 if(q.type==='prescription')return '<div class="answer-review"><h3>Correct answer</h3><p><strong>Rifampicin '+esc(expected[0])+' mg once daily for '+esc(expected[1])+' months.</strong></p><p>Your response: '+esc(selected[0])+' mg daily for '+esc(selected[1])+' months.</p></div>';
 const list=expected.map(i=>'<li><strong>'+esc(q.options[i])+'</strong>'+(q.multi?' <span class="answer-status">'+(selected.includes(i)?'Selected correctly':'Missed')+'</span>':'')+'</li>').join('');
 const wrong=selected.filter(i=>!expected.includes(i));
 return '<div class="answer-review"><h3>'+ (q.multi?'Correct answers — select all of these':'Correct answer')+'</h3><ul>'+list+'</ul>'+(wrong.length?'<h4>Selected incorrectly</h4><ul>'+wrong.map(i=>'<li>'+esc(q.options[i]??'I am not sure')+'</li>').join('')+'</ul>':'')+'</div>';
}
function options(q){return q.type==='prescription'?'<div class="fields"><label>Rifampicin dose (mg daily)<input type="number" min="0" name="dose" required></label><label>Duration (months)<input type="number" min="0" name="duration" required></label></div>':`<div class="options">${q.options.map((o,i)=>`<label class="option"><input type="${q.multi?'checkbox':'radio'}" name="choice" value="${i}" ${q.multi?'':'required'}><span>${o}</span></label>`).join('')}</div>`;}
function values(form,q){if(q.type==='prescription')return [Number(form.elements.dose.value),Number(form.elements.duration.value)];const v=[...form.querySelectorAll('[name=choice]:checked')].map(el=>Number(el.value));if(!v.length)throw Error('Select a response before continuing.');return v;}
function lesson(id){const l=course.lessons.find(l=>l.id===id);if(!l)throw Error('Teaching experience not found.');main.innerHTML=`${btn('Learning pathway','learn')}<div class="eyebrow">${l.phase}</div><h1>${l.title}</h1><p class="intro">${l.lead}</p><div class="objective-box">${l.objective}</div>${l.visual||''}${l.sections.map(([title,text])=>`<section class="teaching-section"><h2>${title}</h2><p>${text}</p></section>`).join('')}${videoButton(l.video)}<div class="table-wrap"><table><thead><tr>${l.table.headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${l.table.rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div><details class="card"><summary>Optional deeper explanation</summary><p>${l.deeper}</p></details><form id="checkpoint" class="card"><h2>Apply the principle</h2><p>${l.checkpoint.q}</p>${options(l.checkpoint)}<button class="btn">Commit and review →</button></form><div id="feedback"></div>`;bindVideos();document.getElementById('checkpoint').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{me=await api('lesson',{id,choice:values(e.target,l.checkpoint)[0]});document.getElementById('feedback').innerHTML=`<section class="feedback"><h2>${me.result.correct?'Correct':'Incorrect'}</h2>${answerReview(l.checkpoint,[values(e.target,l.checkpoint)[0]],me.result.answer)}<h3>Why</h3><p>${me.result.why}</p>${me.result.correct?btn('Continue to patient journey','case/'+l.caseId):'<p>Review the explanation, then try again.</p>'}</section>`;expandClinicalTerms(document.getElementById('feedback'));});};}
function patient(id){const c=course.cases[id];if(!c)throw Error('Patient journey not found.');const responses=me.record.cases[id]||[],index=responses.length,q=c.steps[index];if(!q){main.innerHTML=`<h1>${c.name}’s journey is complete.</h1><p>Your ${responses.length} committed decisions have been saved.</p>${btn('Review the decisions','case-review/'+id)} ${btn('Continue learning','learn')}`;return;}main.innerHTML=`${btn('Learning pathway','learn')}<div class="eyebrow">${c.name} · ${index+1} / ${c.steps.length}</div><h1>${q.stage}</h1><p>${esc(c.age)} · ${esc(c.context)}</p><details class="card"><summary>Patient information</summary>${c.facts.map(([label,value])=>`<p><strong>${label}:</strong> ${value}</p>`).join('')}</details><div class="vignette">${q.text}</div><form id="decision"><h2>${q.question}</h2>${options(q)}<button class="btn">Commit and see feedback →</button></form><div id="feedback"></div>`;document.getElementById('decision').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{me=await api('case',{id,index,values:values(e.target,q)});e.target.dataset.locked='true';e.target.querySelectorAll('input,button').forEach(el=>el.disabled=true);document.getElementById('feedback').innerHTML=`<section class="feedback"><h2>${answerOutcome(me.result.points)}</h2>${answerReview(q,me.record.cases[id][index].values,me.result.answer)}<h3>Why</h3><p>${me.result.why}</p><p><strong>Carry forward:</strong> ${me.result.transfer||''}</p><button class="btn" id="continue">Continue →</button></section>`;expandClinicalTerms(document.getElementById('feedback'));document.getElementById('continue').onclick=()=>render();});};}
async function caseReview(id,ticket){const d=await api('case.review',{id});if(ticket!==renderId)return;main.innerHTML=`<h1>${d.patient.name}’s care, revisited.</h1>${d.patient.steps.map((q,i)=>`<details class="card"><summary>${i+1}. ${q.stage} · ${answerOutcome(d.responses[i].points)}</summary><p>${q.text}</p><h3>${q.question}</h3>${answerReview(q,d.responses[i].values)}<h3>Why</h3><p>${q.why}</p><p><strong>Carry forward:</strong> ${q.transfer||''}</p></details>`).join('')}${btn('Continue learning','learn')}`;}
function exam(){const s=me.record,a=s.attempts.at(-1);main.innerHTML=`<div class="eyebrow">FINAL ASSESSMENT</div><h1>Bring the decisions together.</h1><p class="intro">Ten scenarios. Thirty decisions. Open-reference and untimed.</p><section class="card"><h2>Pass at 21 / 30</h2><p>Each decision contributes up to one point. Multiple-selection items award partial credit for correct selections and deduct for incorrect selections, with a minimum of zero. The server uses the unrounded score.</p><p>Your answers are committed one at a time. Feedback appears after all 30 decisions. If you score below 21, complete the targeted revision before a retake.</p><button class="btn" id="begin">${a&&!a.finished?'Resume assessment':'Begin assessment'} →</button></section>${s.revision.length?`<section class="card"><h2>Your targeted revision</h2>${s.revision.map(id=>`<p>${s.revisionDone.includes(id)?'✓ ':''}<a href="#lesson/${id}">${course.lessons.find(l=>l.id===id)?.title||id}</a></p>`).join('')}</section>`:''}<section class="card"><h2>Saved attempts</h2>${s.attempts.filter(a=>a.finished).map(a=>`<p><a href="#exam-review/${a.id}">${new Date(a.finishedAt).toLocaleDateString('en-SG')} · ${Number(a.score.toFixed(2))}/30 · ${a.passed?'Pass':'Revision and retake'}</a></p>`).join('')||'<p>No completed attempts yet.</p>'}</section>`;document.getElementById('begin').onclick=e=>busy(main,async()=>{me=await api('exam.start');navigate('exam-run');});}
async function examRun(ticket){const d=await api('exam.question');if(ticket!==renderId)return;me=d;const {question:q,index,attemptId,context}=d.result;main.innerHTML=`<div class="eyebrow">FINAL ASSESSMENT · ${index+1} / 30</div><h1>${q.stage}</h1>${context.length?`<section class="scenario-context"><h2>Case information so far</h2>${context.map(t=>`<p>${t}</p>`).join('')}</section>`:''}<div class="vignette">${q.text}</div><form id="decision"><h2>${q.question}</h2>${options(q)}<p>Your answer is saved when you commit. Feedback follows submission of all 30 decisions.</p><button class="btn">${index===29?'Submit final decision':'Commit and continue'} →</button></form>`;document.getElementById('decision').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{me=await api('exam.answer',{attemptId,index,values:values(e.target,q)});navigate(index===29?'exam-review/'+attemptId:'exam-run');});};}
async function examReview(id,ticket){const d=await api('exam.review',{id});if(ticket!==renderId)return;main.innerHTML=`<h1>${d.attempt.passed?'Assessment passed.':'Review, revise and return.'}</h1><div class="score">${Number(d.attempt.score.toFixed(2))} / 30</div><p>Pass threshold: 21/30. All attempts remain in your course record.</p>${d.questions.map((q,i)=>`<details class="card"><summary>${i+1}. ${q.stage} · ${answerOutcome(d.attempt.answers[i].points)} · ${Number(d.attempt.answers[i].points.toFixed(2))}/1</summary><p>${q.text}</p><h3>${q.question}</h3>${answerReview(q,d.attempt.answers[i].values)}<h3>Why</h3><p>${q.why}</p><p>${q.transfer||''}</p></details>`).join('')}<div class="actions">${btn('Reflect on your learning','reflection')} ${btn('Revision and assessment','exam')}</div>`;}
async function reflectionReview(ticket){const d=await api('reflection.review');if(ticket!==renderId)return;main.innerHTML=`<h1>Knowledge and confidence, side by side.</h1><section class="card"><h2>Knowledge check</h2><p>Starting point: ${d.pre.score}/10 · Closing check: ${d.post.score}/10</p><p>These are matched questions. Change can reflect both learning and familiarity.</p></section><section class="card"><h2>Your confidence</h2>${me.confidenceAreas.map(([id,label])=>`<p>${label}: ${d.pre.confidence[id]??'Not rated'} → ${d.post.confidence[id]??'Not rated'}</p>`).join('')}</section>${d.questions.map(q=>`<details class="card"><summary>${q.question} · ${answerOutcome(d.post.answers[q.id]===q.answer?1:0)}</summary><p>${q.stem}</p><p><strong>Warm-up:</strong> ${answerOutcome(d.pre.answers[q.id]===q.answer?1:0)} — ${esc(q.options[d.pre.answers[q.id]]||'I am not sure')}</p><p><strong>Closing check:</strong> ${answerOutcome(d.post.answers[q.id]===q.answer?1:0)} — ${esc(q.options[d.post.answers[q.id]]||'I am not sure')}</p>${answerReview(q,[d.post.answers[q.id]])}<h3>Why</h3><p>${q.why}</p></details>`).join('')}${btn('Completion certificate','certificate')}`;}
function references(){main.innerHTML=`<h1>Clinical references</h1><p>Use the teaching pages for the course’s local care policy. Public references below support the clinical principles.</p><section class="card">${Object.entries(course.refs).filter(([k,url])=>/^https:\/\//.test(url)).sort(([a],[b])=>a==='sg'?-1:b==='sg'?1:0).map(([k,url])=>`<p><a href="${esc(url)}" target="_blank" rel="noopener">${k==='sg'?'singapore':esc(k)} ↗</a></p>`).join('')}</section>${btn('Learning pathway','learn')}`;}
function record(){const s=me.record;profile(true);main.insertAdjacentHTML('beforeend',`<h2>Your learning record</h2><p>Your submitted work is stored in your course account and is available across devices.</p><section class="card"><p>Clinical warm-up: ${s.pre?'Complete':'To do'}</p><p>Teaching experiences: ${Object.keys(s.lessons).length}/9</p><p>Patient journeys: ${course?course.caseOrder.filter(id=>s.cases[id]?.length===course.cases[id].steps.length).length:0}/9</p><p>Final assessment: ${s.attempts.some(a=>a.finished&&a.passed)?'Passed':'To complete'}</p><p>Closing reflection: ${s.post?'Complete':'To do'}</p></section><div class="actions">${btn('Your certificate','certificate')}${btn('Continue learning','learn')}</div><button class="text-btn" id="download-record">Download my response record</button>`);document.getElementById('download-record').onclick=()=>download('tuberculum-learning-record.json',{profile:me.profile,record:s});}
async function certificate(ticket){
const s=me.record,lessons=course?course.lessons.filter(l=>s.lessons[l.id]).length:0,journeys=course?course.caseOrder.filter(id=>s.cases[id]?.length===course.cases[id].steps.length).length:0;
const requirements=[
[!!s.pre,'Clinical warm-up','home'],
[lessons===9,'Teaching experiences ('+lessons+'/9)','learn'],
[journeys===9,'Patient journeys ('+journeys+'/9)','learn'],
[s.attempts.some(a=>a.finished&&a.passed),'Final assessment passed (21/30 or above)','exam'],
[!!s.post,'Closing reflection','reflection']
];
if(!me.profile)requirements.unshift([false,'Learner profile','profile']);
if(requirements.some(([done])=>!done)){
main.innerHTML=`<h1>Your completion certificate</h1><p>Complete the remaining items to receive your certificate.</p><section class="card" aria-label="Certificate requirements">${requirements.map(([done,label,route])=>`<div class="outcome-row"><span>${done?'✓':'○'} ${esc(label)}</span>${done?'<span class="small">Complete</span>':`<a href="#${route}" class="text-btn">To do →</a>`}</div>`).join('')}</section>`;return;
}
const d=await api('certificate');if(ticket!==renderId)return;const c=d.certificate;main.innerHTML=`<div class="no-print"><h1>Your completion certificate</h1><p>This certificate was issued from your verified course completion record.</p><button class="btn" id="print">Print / save as PDF</button></div><section class="certificate"><div class="eyebrow">TUBERCULUM</div><h1>Certificate of completion</h1><h2>${esc(c.learner_name)}</h2><p>has completed</p><h2>TB infection care in general practice</h2><p>Singapore · 4R and 6H preventive care</p><p>Completed the learning pathway and passed the final assessment.</p><p>Issued ${new Date(c.issued_at).toLocaleDateString('en-SG')}</p><p class="small">Certificate ${esc(c.id)}<br>Course version ${esc(c.course_version)}</p></section>`;document.getElementById('print').onclick=()=>window.print();}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function adminPage(ticket){const d=await api('admin.list');if(ticket!==renderId)return;main.innerHTML=`<div class="eyebrow">ADMINISTRATOR</div><h1>Your course community.</h1><section class="card"><h2>Invite learners</h2><p>Create personal links, then share each link privately with its named recipient. Links expire in seven days and can be used once. This page does not send email.</p><form id="invite" class="fields"><label>Email addresses<textarea name="emails" rows="4" placeholder="One email per line" required></textarea></label><label>Or import a CSV containing email addresses<input id="csv" type="file" accept=".csv,text/csv"></label><label>Link type<select name="purpose"><option value="invite">New learner invitation</option><option value="recovery">Existing account password recovery</option></select></label><button class="btn">Create personal links →</button></form><div id="links"></div></section><section class="card admin-only"><h2>Learners and progress</h2><button id="export" class="text-btn">Export course records (JSON)</button><table class="admin-table"><thead><tr><th>Learner</th><th>Progress</th><th>Actions</th></tr></thead><tbody>${d.learners.map(l=>{const r=l.record||{};return `<tr><td>${esc(l.full_name||l.email)}<br>${esc(l.email)}<br><small>${esc(l.role)} · ${l.active===null?'Registration incomplete':l.active?'Active':'Inactive'}</small></td><td>${Object.keys(r.lessons||{}).length}/9 teaching<br>${Object.values(r.cases||{}).filter(a=>a.length).length} journeys started<br>${(r.attempts||[]).filter(a=>a.finished).length} assessment attempts<br>${(r.attempts||[]).some(a=>a.passed)?'Assessment passed':''}</td><td>${l.active!==null?`<button class="text-btn" data-access="${l.user_id}" data-active="${!l.active}">${l.active?'Deactivate':'Reactivate'}</button>`:''}${l.role!=='admin'?`<button class="text-btn" data-delete="${l.user_id}">Delete account</button>`:''}${l.certificate_id&&!l.revoked_at?`<button class="text-btn" data-cert="${l.certificate_id}">Revoke certificate</button>`:''}</td></tr>`;}).join('')}</tbody></table></section><section class="card"><h2>Invitations</h2>${d.invitations.map(i=>`<p>${esc(i.email)} · ${esc(i.purpose)} · ${i.status==='pending'&&Date.parse(i.expires_at)<Date.now()?'expired':esc(i.status)} ${i.status==='pending'?`<button class="text-btn" data-invite="${i.id}">Revoke</button>`:''}</p>`).join('')}</section>`;
 const form=document.getElementById('invite');document.getElementById('csv').onchange=async e=>{const text=await e.target.files[0]?.text();if(text)form.elements.emails.value=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]).join('\n');};
 form.onsubmit=e=>{e.preventDefault();busy(form,async()=>{const f=new FormData(form);const d=await api('admin.invite',{emails:String(f.get('emails')).split(/[\s,;]+/).filter(Boolean),purpose:f.get('purpose')});document.getElementById('links').innerHTML=d.links.map(l=>`<div class="card link-output"><strong>${esc(l.email)}</strong><p>${l.error?esc(l.error):`<input readonly aria-label="Personal link for ${esc(l.email)}" value="${esc(l.url)}">`}</p></div>`).join('');});};
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>busy(main,async()=>{const learner=d.learners.find(l=>l.user_id===b.dataset.delete);const email=prompt('Permanently delete '+learner.email+'? This removes their account, profile, responses, progress and certificate records. This cannot be undone. Previously downloaded files cannot be recalled. They can sign up again because registration is open. To suspend access instead, use Deactivate.\n\nType their email address to confirm:');if(email===null)return;if(email.trim().toLowerCase()!==learner.email.toLowerCase())throw Error('The email address does not match. Nothing was deleted.');await api('admin.deleteAccount',{id:learner.user_id,confirmEmail:email});render();}));
 document.getElementById('export').onclick=()=>download('tuberculum-course-records.json',d);
 document.querySelectorAll('[data-access]').forEach(b=>b.onclick=()=>busy(main,async()=>{await api('admin.access',{id:b.dataset.access,active:b.dataset.active==='true'});render();}));
 document.querySelectorAll('[data-invite]').forEach(b=>b.onclick=()=>busy(main,async()=>{await api('admin.revokeInvite',{id:b.dataset.invite});render();}));
 document.querySelectorAll('[data-cert]').forEach(b=>b.onclick=()=>busy(main,async()=>{if(!confirm('Revoke this certificate?'))return;await api('admin.revokeCertificate',{id:b.dataset.cert});render();}));
}
async function render(){const ticket=++renderId;main.removeAttribute('data-acronyms-defined');try{let route=location.hash.slice(1)||'home';const callback=new URLSearchParams(route);if(callback.has('access_token')||callback.has('error')){history.replaceState(null,'','#signin');signin();if(callback.has('error'))error('This confirmation link has expired or could not be verified. Try signing in. If you still cannot access your account, contact tuberculum.course@gmail.com.');else main.insertAdjacentHTML('afterbegin','<p class="notice" role="status">Your email link has been processed. Sign in to continue.</p>');return;}nav();if(route==='privacy'){privacy();return;}if(route.startsWith('accept/')){accept(route.split('/')[1]);return;}if(!session&&route==='signup'){signup();return;}if(!session){signin();return;}main.innerHTML='<p>Loading your saved course record…</p>';me=await api('me');if(ticket!==renderId)return;nav();if(me.role==='admin'&&route==='admin'){await adminPage(ticket);return;}if(route==='certificate'&&(!me.profile||!me.record.pre)){await certificate(ticket);return;}if(!me.profile){profile();return;}if(['account','profile','record'].includes(route)){if(me.record.pre&&!course)course=await api('content');if(ticket!==renderId)return;record();return;}if(!me.record.pre){evaluationForm(false);return;}if(!course)course=await api('content');if(ticket!==renderId)return;
 if(route==='learn')pathway();else if(route.startsWith('lesson/'))lesson(route.split('/')[1]);else if(route.startsWith('case/'))patient(route.split('/')[1]);else if(route.startsWith('case-review/'))await caseReview(route.split('/')[1],ticket);else if(route==='exam')exam();else if(route==='exam-run')await examRun(ticket);else if(route.startsWith('exam-review/'))await examReview(route.split('/')[1],ticket);else if(route==='reflection'){if(me.record.post)await reflectionReview(ticket);else evaluationForm(true);}else if(route==='reflection-review')await reflectionReview(ticket);else if(route==='certificate')await certificate(ticket);else if(route==='reference')references();else home();if(route==='home'||route==='learn'||route.startsWith('lesson/')||route.startsWith('case/')||route.startsWith('case-review/'))expandClinicalTerms();main.focus({preventScroll:true});window.scrollTo(0,0);
 }catch(e){if(ticket!==renderId)return;if(!session){me=null;nav();signin();}else main.innerHTML=`<h1>Let’s check your next step.</h1>${btn('Learning pathway','learn')} ${btn('Assessment','exam')} ${btn('Learning record','record')}`;error(e);}}
window.addEventListener('hashchange',render);document.querySelector('#video .close').onclick=()=>document.getElementById('video').close();document.getElementById('video').addEventListener('close',()=>document.getElementById('video-content').innerHTML='');render();
