/* Tuberculum curriculum: independently editable teaching and assessment content.
   Clinical-review edition 2.0.0. No learner identifiers or patient records. */
const courseVersion='2.1.0';
Object.assign(refs,{igra:'https://www.cdc.gov/tb/hcp/testing-diagnosis/interferon-gamma-release-assay.html',diagnosis:'https://www.cdc.gov/tb/hcp/testing-diagnosis/clinical-and-laboratory-diagnosis.html',notification:'https://www.moh.gov.sg/seeking-healthcare/overview-of-diseases/communicable-diseases/infectious-disease-notification/',sg:'https://annals.edu.sg/singapore-tuberculosis-clinical-management-guidelines-2024/'});
const lessonData=[
{id:'biology',phase:'Understand',title:'Infection, disease and infectiousness',time:12,video:3,caseId:'mei',objective:'Explain TB natural history and distinguish infection, disease and infectiousness in a patient conversation.',lead:'Three clinical questions need different kinds of evidence.',sections:[
['Start with transmission','TB is acquired through inhaling airborne particles containing Mycobacterium tuberculosis. Risk depends on the source, exposure circumstances, ventilation and the person exposed. Close, prolonged indoor contact matters, but neither a history of exposure nor belonging to a demographic group establishes infection. Frame risk around circumstances rather than blame.'],
['From biology to a clinical distinction','After infection, outcomes vary. Host immune responses can contain infection, while some people develop disease. Recent infection and impaired immunity are important when considering progression risk. The biology includes a spectrum of bacterial activity and host responses; the clinical labels help organise care without describing every biological state. TB disease can be subclinical or have atypical symptoms.'],
['What you can explain to a patient','TB infection, conventionally called latent TB infection, means infection without evidence of TB disease after appropriate assessment. TB infection alone is not infectious. TB disease may involve the lungs or other organs. Pulmonary and laryngeal disease are the principal transmission concern; do not infer that every person with TB disease is equally infectious.'],
['Treatment and infectiousness','Effective treatment can reduce infectiousness before the entire treatment course ends. Clearance decisions depend on the clinical and public-health assessment, including treatment effectiveness and response. Do not promise a universal date or use an IGRA value to decide when precautions can end.']
],table:{headers:['Question','Evidence to consider'],rows:[['Evidence of infection?','IGRA/TST, interpreted in context'],['Evidence of disease?','History, examination, imaging and appropriate microbiology'],['Potential to transmit?','Disease site, respiratory findings, microbiology and treatment context']]},deeper:'An IGRA measures an immune response, not a direct census of viable bacteria. A positive result cannot establish how many organisms remain, the anatomical site, or the date of infection. Avoid describing a test as proving that live bacteria are sleeping in a particular granuloma.',ref:'overview',checkpoint:{q:'A clinically assessed patient has TB infection without TB disease and asks whether to sleep separately from their family. Which explanation is appropriate?',options:['Separation is needed until preventive treatment is complete.','TB infection alone is not infectious; preventive treatment aims to reduce the risk of future disease.','Repeat IGRA is needed before advising about household contact.'],answer:1,why:'Infectiousness is not determined by the positive infection test. Appropriate assessment has established TB infection without disease.'}},
{id:'testing',phase:'Understand',title:'Ask the test the right question',time:15,video:0,caseId:'daniel',objective:'Choose and interpret infection tests, including negative and indeterminate results.',lead:'Begin with why you are testing and what you would do with the result.',sections:[
['A test should serve a decision','Assess the likelihood of infection and the importance of preventing disease before ordering a test. Contact history, source infectiousness, immune status and previous testing or treatment help define the question. Testing without considering downstream assessment and treatment can create uncertainty without a useful plan.'],
['IGRA and TST','Both tests detect immune responses compatible with infection. BCG vaccination can influence TST results; it does not cause a positive IGRA. TST interpretation depends on induration, risk and the relevant guideline. Do not teach a single universal cut-off or substitute the area of erythema for induration. Practical test choice also depends on age, access and the ability to return for reading.'],
['Negative is contextual','A recent contact may be tested before a detectable response develops. CDC advises repeat infection testing 8–10 weeks after the last exposure for contacts with an initially negative test, as an international reference. Singapore contact-screening timing should follow the approved local pathway. Symptoms or concerning imaging require disease evaluation now rather than waiting for repeat infection testing.'],
['Indeterminate is not negative','Review the reported controls, specimen-handling issues and the person’s clinical context. Repeat IGRA or a different infection test may be useful if a reason to test persists. Immunosuppression can complicate interpretation. An uninformative test cannot provide reassurance about TB disease.'],
['Previous results remain useful','Retrieve documented previous positive results and treatment details. Infection tests may remain positive after successful preventive treatment. Repeating them to prove cure or to judge adherence does not answer those questions.']
],table:{headers:['Result','Next reasoning step'],rows:[['Positive','Evaluate for disease and then assess preventive-care suitability'],['Negative','Consider timing and immune status; investigate disease when clinically indicated'],['Indeterminate / invalid','Review why the test is uninformative and plan further assessment']]},deeper:'Conversions, reversions and results close to an assay threshold need contextual interpretation. A numeric IGRA change is not automatically a change in disease probability or proof of new infection. Specialist advice is useful when repeat results conflict and the treatment decision is consequential.',ref:'igra',checkpoint:{q:'An asymptomatic adult contact has an indeterminate IGRA. What is the most defensible interpretation?',options:['The patient has no TB infection because the assay did not report positive.','TB disease is established and treatment should start.','The test is uninformative; review the context and arrange an appropriate next test or assessment.'],answer:2,why:'An indeterminate result does not classify the person as uninfected. The clinical reason for testing remains.'}},
{id:'disease',phase:'Recognise',title:'Recognise possible TB disease',time:18,video:1,caseId:'rahman',objective:'Recognise a concerning presentation and coordinate initial precautions, evaluation and referral.',lead:'The clinical picture can outweigh an apparently reassuring test.',sections:[
['Consider the pattern, not a single symptom','Persistent cough, constitutional symptoms, haemoptysis and weight loss should prompt consideration of pulmonary TB in context. Extrapulmonary disease may present differently, such as persistent lymphadenopathy. Older age or immunosuppression can alter the presentation. Neither absence of fever nor lack of a known contact reliably removes the possibility.'],
['Use radiology with the clinical history','Cavitation or other compatible changes can increase concern, but imaging is not specific for TB. A previous film can help establish change. A label such as old scarring should be reconciled with symptoms, prior treatment and comparison imaging. Synthetic CXR illustrations accompany supplied reports. Use the clinical history and report for decisions; the illustrations are awaiting expert image review.'],
['Understand complementary microbiology','Smear microscopy is rapid but neither fully sensitive nor specific for M. tuberculosis. Molecular testing can provide rapid evidence and some resistance information. Culture can confirm the organism and enable susceptibility testing. Negative initial tests may not settle a case with substantial clinical suspicion. Specimen quality and the disease site matter.'],
['Act while arranging the next step','For possible infectious pulmonary disease, provide appropriate source control, reduce exposure to others and follow local respiratory-protection arrangements. Coordinate appropriate specimen collection in a suitable setting. Do not ask a patient to induce sputum in a shared consultation space. Arrange NTBCC evaluation without waiting for every result. An acutely unwell patient needs emergency care.'],
['Notification and handover','Singapore requires notification of suspected or confirmed TB cases through the official process. Referral is a separate action. Communicate symptoms, imaging, specimen status, relevant history and interim precautions. Agree who will trace pending results and confirm attendance. The operational notification deadline and form should be checked against current official instructions.']
],table:{headers:['Evidence','Important limitation'],rows:[['Compatible CXR','Supports suspicion; does not establish a unique diagnosis'],['Negative smear','Does not exclude TB disease'],['Negative molecular test','May not exclude disease in a high-suspicion presentation'],['Positive M. tuberculosis culture','Confirms disease; susceptibility still informs treatment']]},deeper:'The number and timing of specimens are operational protocol details. International and local recommendations can differ. The competence assessed here is selecting appropriate microbiology and arranging safe collection and follow-up, not recalling an unapproved local specimen count.',ref:'diagnosis',checkpoint:{q:'A patient with weight loss and a cavity has negative initial sputum smear and molecular testing. What follows?',options:['Continue evaluation through the TB disease pathway; the negative results do not settle the concerning presentation.','Reclassify as uncomplicated TB infection and begin preventive treatment.','Close the TB evaluation and repeat the IGRA at routine review.'],answer:0,why:'Negative initial microbiology may occur with TB disease. Clinical suspicion determines the need for continuing investigation.'}},
{id:'exclude',phase:'Recognise',title:'The checkpoint before prevention',time:15,video:1,caseId:'lim',objective:'Integrate evidence to proceed with preventive care, defer for investigation or seek specialist support.',lead:'A positive infection test starts an assessment; it does not complete one.',sections:[
['Bring the information together','Review symptoms, medical history, prior TB disease or preventive treatment, examination and chest imaging. Consider the source isolate’s susceptibility where available. Ask about HIV and other immunosuppression with appropriate clinical sensitivity. Investigate symptoms or abnormal findings as indicated.'],
['Decide whether enough is known','An asymptomatic immunocompetent adult with a reassuring examination and normal CXR may proceed to assessment for preventive treatment when the remaining information supports it. This is not an instruction to obtain sputum from every well person. Equally, an abnormal CXR or unresolved symptoms may require microbiology or specialist evaluation before treatment.'],
['Do not force uncertainty into a binary label','It can be correct to say that TB disease has not yet been sufficiently excluded. A pending investigation, an unexplained abnormality or an incomplete history may change the decision. Record what is unresolved, who will investigate it and how follow-up will occur.'],
['Assess treatment suitability separately','After disease exclusion, evaluate medication interactions, hepatic risk, allergies, pregnancy where relevant, previous treatment, likely drug susceptibility and the person’s priorities. A patient can be suitable for preventive care but unsuitable for a particular regimen.'],
['Keep uncomplicated care in general practice','Referral is not the default endpoint of a positive IGRA. A straightforward adult case can remain with the GP. Diagnostic uncertainty, substantial interactions or special clinical circumstances can call for NTBSC support; concern about TB disease redirects to the disease pathway.']
],table:{headers:['Situation','Decision'],rows:[['Assessment complete and reassuring','Discuss benefits, harms and regimen suitability'],['Symptoms or unexplained imaging findings','Defer prevention while evaluating possible disease'],['Disease excluded, regimen complexity remains','Seek focused specialist advice and maintain follow-up']]},deeper:'Disease exclusion is a clinical judgement made using appropriate evidence; it is not a claim of absolute zero probability. State the basis of the judgement and provide advice about new symptoms, including during preventive treatment.',ref:'overview',checkpoint:{q:'A positive IGRA is followed by a CXR report of apical changes of uncertain chronicity. The patient has no symptoms. What is the appropriate approach?',options:['Start treatment because absence of symptoms excludes disease.','Clarify the imaging and prior history, and arrange further evaluation where indicated before preventive treatment.','Repeat IGRA until a negative result resolves the imaging uncertainty.'],answer:1,why:'An unexplained abnormality needs clinical reconciliation. Repeating the infection test cannot establish what the imaging represents.'}},
{id:'decision',phase:'Prevent',title:'A preventive decision the patient understands',time:15,video:4,caseId:'siti',objective:'Explain benefits and harms, elicit priorities, and support an informed choice.',lead:'A good decision includes both the evidence and the person living with the plan.',sections:[
['Explain the purpose','The patient may feel entirely well. Explain that the aim is to reduce the chance of future TB disease, not to treat current symptoms. First check what the patient understands about the test and whether they are worried about being infectious, family safety or stigma.'],
['Discuss risk honestly','Risk varies with recency of infection, immune status and other clinical factors. Treatment benefit depends on baseline risk as well as regimen efficacy and completion. Avoid converting a broad lifetime estimate into a precise personal prediction. State uncertainty, the relevant timeframe and what could alter risk.'],
['Discuss burden as well as benefit','Explain duration, daily routines, expected effects, important adverse symptoms, interactions and monitoring. Ask about work schedules, caring responsibilities, costs and access to follow-up rather than assuming that a short regimen is automatically easy. Practical barriers are care problems to solve together.'],
['Respond to the patient’s priorities','Use open questions, plain language and teach-back. If the patient asks about family contact, address infection versus disease before discussing tablets. If they are afraid of liver injury, explain warning symptoms and the monitoring plan rather than saying treatment is risk-free.'],
['Respect the decision','The patient may wish to start, take time or decline. Document the conversation, preferences and agreed plan. Provide symptom safety-netting and follow-up appropriate to the local pathway. A decision to decline does not prove poor counselling. Revisit if risk factors, circumstances or preferences change.']
],table:{headers:['Instead of','Try'],rows:[['You must take this because the test is positive.','Let us discuss what treatment could offer you and what concerns you.'],['Your exact future risk is this population percentage.','Your risk depends on several factors; here is what matters in your case.'],['Do you understand?','How would you explain the plan and warning symptoms in your own words?']]},deeper:'Useful risk graphics show the same denominator and timeframe for treated and untreated groups, with the underlying population and uncertainty stated. An illustrative icon array is not an individualised calculator. Do not generate patient-specific probabilities without a validated method and appropriate inputs.',ref:'treatment',checkpoint:{q:'A patient understands the benefit but wants time to consider treatment. Which action best supports shared decision-making?',options:['Record that preventive treatment has failed.','Use the risk of infecting family members from TB infection to persuade them.','Explore remaining concerns, offer clear information and agree a follow-up conversation.'],answer:2,why:'Allowing time and addressing the person’s concerns supports an informed decision. TB infection alone is not infectious.'}},
{id:'prescribe',phase:'Prevent',title:'From regimen choice to a safe prescription',time:20,video:2,caseId:'anita',objective:'Choose an appropriate regimen, check interactions and produce a complete prescription.',lead:'The medication review is part of the treatment decision.',sections:[
['The principal worked regimen','The course uses four months of daily rifampicin (4R) for uncomplicated adult examples when suitable. Check the indication, weight, source susceptibility if available, interactions, allergies and relevant comorbidity first. TB disease must have been appropriately excluded.'],
['Know the alternatives without treating them as interchangeable','Isoniazid-based options may be appropriate when a rifamycin is unsuitable, but have their own toxicity, adherence and susceptibility considerations. Shorter rifapentine regimens appear in international guidance. Their local availability, indications and place in GP prescribing need confirmation; they are enrichment rather than an automatic substitution in this course.'],
['Review all medicines','Include prescriptions from other clinicians, over-the-counter preparations, supplements and hormonal contraception. Use an up-to-date interaction reference. Rifampicin can alter the exposure or effect of many medicines through enzyme and transporter effects. Separating doses is not a general solution.'],
['Coordinate an interaction plan','Identify whether the combination should be avoided, an alternative selected or specialist monitoring arranged. The plan may involve the clinician managing anticoagulation, HIV or another condition. Think ahead to stopping rifampicin, when previous medication adjustments may also need review.'],
['Complete the prescribing task','Document drug, dose, oral route, frequency, intended duration and start date, using the appropriate formulation and dispensing quantity. Explain administration, anticipated effects, missed-dose advice and when to seek help. For isoniazid, assess the need for pyridoxine and use the approved local dosing policy.']
],table:{headers:['Adult regimen reference','Dose and duration','Clinical consideration'],rows:[['4R','Rifampicin 10 mg/kg daily, maximum 600 mg; 4 months','Medication interactions; source susceptibility'],['6H','Isoniazid 5 mg/kg daily, maximum 300 mg; 6 months','Hepatotoxicity, neuropathy risk and pyridoxine']]},deeper:'The table summarises internationally recognised adult dosing, not a prescription for every patient. Paediatric dosing differs. Renal/hepatic disease, pregnancy, HIV treatment and resistant-source contacts need context-specific decisions. This course teaches recognition and consultation rather than unsupervised specialist regimen selection.',ref:'treatment',checkpoint:{q:'A patient takes a medicine with a significant rifampicin interaction. Which is the general rule?',options:['Check the specific interaction and establish an alternative or coordinated management plan before prescribing.','Move the interacting medicine to bedtime without further assessment.','Use 4R unchanged because preventive doses do not cause interactions.'],answer:0,why:'The interaction depends on the specific medicine and clinical context. Preventive use of rifampicin does not remove its interaction potential.'}},
{id:'monitor',phase:'Continue care',title:'The follow-up that changes care',time:20,video:5,caseId:'chen',objective:'Respond to adherence problems, new symptoms and laboratory abnormalities during treatment.',lead:'A scheduled review and a reliable route for urgent advice serve different purposes.',sections:[
['Review more than tablet taking','Ask about missed doses without blame, symptoms of TB disease, adverse effects and newly started medicines. Clarify what the patient actually takes and whether practical barriers have changed. Check that the patient knows how to reach the practice between appointments.'],
['Plan clinical and laboratory review separately','CDC recommends at least monthly clinical review during preventive treatment. Baseline and repeat liver tests are risk-based in that guidance, including liver disease, abnormal baseline results and relevant clinical circumstances. Singapore implementation may use a different approved baseline policy. A clinical-review interval does not itself specify a nurse-led model or mandatory monthly blood tests for every person.'],
['Act on symptoms before a threshold arrives','New persistent nausea, anorexia, jaundice or dark brown urine warrants withholding treatment and prompt clinical assessment for possible hepatitis. Do not wait for the next scheduled visit. Assess severity and other diagnoses. Acute illness, severe hypersensitivity or signs of organ dysfunction need urgent escalation.'],
['Interpret liver tests in context','As an international reference, CDC advises withholding medication when transaminases exceed three times the upper limit of normal with symptoms or five times without symptoms. Symptoms can require action even before those thresholds are met. Baseline abnormalities, trends and bilirubin affect assessment. Use the locally approved protocol and seek specialist advice where appropriate.'],
['Differentiate expected effects and danger signs','Orange discolouration of body fluids with rifampicin can be expected. Persistent dark urine with systemic symptoms is different. A new rash needs assessment; mucosal lesions, fever, facial swelling, respiratory symptoms or systemic illness increase urgency. Do not advise unsupervised rechallenge after a serious reaction.']
],table:{headers:['Encounter','Response'],rows:[['Missed doses, otherwise well','Explore barriers and reconcile actual treatment; agree a plan'],['New persistent nausea and jaundice','Withhold treatment; urgent clinical assessment'],['Rash with mucosal or systemic features','Stop treatment and arrange urgent care'],['New medicine','Repeat the interaction assessment']]},deeper:'A remote review can support some follow-up when clinically appropriate, but it must include escalation routes and access to examination or laboratory testing when needed. Suitability is a clinical and service decision, not determined simply by the absence of a previous adverse effect.',ref:'treatment',checkpoint:{q:'A patient is jaundiced and nauseated but their scheduled blood test is next week. What should you advise?',options:['Continue until the booked test because no result is available yet.','Withhold treatment and arrange urgent assessment now.','Take treatment every other day until the next review.'],answer:1,why:'Potential hepatitis requires action based on symptoms. Waiting for routine monitoring risks delayed recognition of serious injury.'}},
{id:'complex',phase:'Continue care',title:'Recognise when the plan needs support',time:18,video:6,caseId:'priya',objective:'Identify complex TB infection and arrange focused NTBSC advice while retaining continuity.',lead:'The right escalation is specific about the clinical question.',sections:[
['Recognise the boundaries','Pregnancy, young children, substantial immunosuppression, HIV treatment, important liver disease, difficult interactions, prior treatment uncertainty and resistant-source contacts can require specialist input. These are reasons to assess complexity, not labels that make preventive treatment universally impossible.'],
['Think about time as well as regimen','A patient about to start immunosuppression needs coordination with the treating specialty. A young child or immunocompromised contact may need action despite an early negative test. Do not apply the routine adult retesting plan without considering their risk.'],
['Pregnancy and resistant-source contacts','Pregnancy decisions balance maternal risk, timing, regimen and monitoring; avoid a blanket instruction to wait until after delivery. For an MDR/RR-TB contact, routine drug-susceptible preventive regimens should not be assumed appropriate. WHO’s 2024 guidance includes a preventive-treatment recommendation in this setting, requiring expert assessment and local implementation.'],
['Ask a focused question','Send the infection result, disease-exclusion evidence, source susceptibility if known, medication list, relevant comorbidity, baseline results and patient preferences. State whether you need help with diagnostic uncertainty, regimen selection, interactions or timing. Confirm the receiving service and urgency.'],
['Maintain continuity','An advice request does not end the GP’s responsibility for the agreed interim plan. Document who will review the response, contact the patient and trace pending results. TB disease concern directs to NTBCC; complex TB infection support directs to NTBSC. Acute instability directs to emergency care.']
],table:{headers:['Complexity','Question to resolve'],rows:[['Planned immunosuppression','Timing, risk and coordination with the treating specialty'],['Resistant source isolate','Which preventive approach is suitable?'],['Pregnancy','What timing and regimen fit this patient’s risk?'],['Major interaction','Can an alternative or coordinated plan be used?']]},deeper:'The optional specialist reading is for understanding the referral question. It does not extend the assessed prescribing scope to paediatric, resistant-TB or other specialist treatment. A full GP scope policy should distinguish advice, shared care and transfer of care.',ref:'who',checkpoint:{q:'A young child is a recent household contact with an early negative infection test. What is appropriate?',options:['Use the routine adult plan and wait without further assessment.','Assume infection has been excluded.','Arrange prompt specialist contact assessment; early testing and vulnerability affect the plan.'],answer:2,why:'Young children can require specialist assessment and preventive action despite an early negative test. The uncomplicated adult pathway should not be applied automatically.'}},
{id:'completion',phase:'Continue care',title:'Completion, interruptions and the next encounter',time:15,video:7,caseId:'kumar',objective:'Reconcile treatment received, document outcomes and provide appropriate post-treatment advice.',lead:'Elapsed time is not the same as treatment completed.',sections:[
['Reconcile what was actually taken','Use the documented regimen, start date, dispensing information and the patient’s account of missed doses. Record the extent and timing of interruptions. Do not classify a course as complete just because four calendar months passed. Use the approved dose-count and maximum-duration rules for the regimen.'],
['Handle interruptions as a clinical decision','Ask why treatment stopped, whether there are new symptoms and whether medicines or circumstances changed. Assess the need to revisit disease exclusion. A substantial interruption may need specialist advice about extending, restarting or changing the plan. Do not tell the patient to double doses to catch up.'],
['Close the record','Document the original infection test, relevant imaging, regimen, dose, treatment dates, doses received where available, interruptions and the conclusion reached. Provide a treatment record the patient can retain. Make clear whether treatment was completed, stopped early or remains in progress.'],
['Explain what happens to the test','An IGRA or TST may remain positive after treatment. Do not repeat it as a test of cure. An unchanged result does not prove treatment failed. New symptoms or significant re-exposure require a fresh clinical assessment using the previous treatment record.'],
['Provide future advice','Explain symptoms that should prompt review and make sure the patient knows where to seek help. Follow the locally approved pathway for ongoing follow-up, including when treatment is declined or incomplete. Avoid inventing a universal radiographic surveillance schedule.']
],table:{headers:['Question','Use'],rows:[['Was treatment completed?','Regimen-specific completion criteria and treatment record'],['Did the IGRA become negative?','Not a valid measure of preventive-treatment success'],['What if new symptoms develop?','Clinical evaluation for disease, regardless of past treatment'],['What if there is new exposure?','Individual reassessment with previous records']]},deeper:'Service outcomes such as uptake and completion are useful, but interpreting them requires context. An informed decision to decline, a toxicity-related cessation and loss to follow-up describe different situations and should not be collapsed into one judgement of patient behaviour.',ref:'treatment',checkpoint:{q:'A patient has taken preventive treatment for four calendar months but reports a prolonged interruption. What establishes completion?',options:['Reconcile treatment received against the approved regimen-specific completion criteria.','The four-month anniversary of the first prescription.','A repeat negative IGRA.'],answer:0,why:'The treatment record and completion rules determine the outcome. Calendar duration alone is insufficient.'}}
];
videos.push(
{title:'Why treat someone who feels well?',duration:'4 min',question:'How do I explain preventive benefit fairly?',message:'Discuss the patient’s risk, treatment burden, uncertainty and preferences. An informed decision is the aim.',objective:'Support shared decision-making without coercion.',next:'Practise a conversation about a patient’s concerns.'},
{title:'The follow-up that matters',duration:'4 min',question:'What should change today’s plan?',message:'Review symptoms, actual doses, new medicines and barriers; distinguish routine review from urgent assessment.',objective:'Recognise toxicity and support continuity.',next:'Triage follow-up calls and interpret laboratory results.'},
{title:'When to ask for specialist support',duration:'4 min',question:'What makes this case complex?',message:'Identify the specific risk, send a focused handover and retain an agreed interim plan.',objective:'Coordinate NTBSC support for complex TB infection.',next:'Manage a time-sensitive immunosuppression scenario.'},
{title:'Finishing the course of treatment',duration:'3 min',question:'What evidence establishes completion?',message:'Reconcile actual treatment with the regimen criteria, document the outcome and explain future advice.',objective:'Manage interruptions and post-treatment counselling.',next:'Review a treatment record with missed doses.'}
);
const Q=(stage,text,question,options,answer,why,transfer,ref='treatment',multi=false)=>({stage,text,question,options,answer,why,transfer,ref,multi});
Object.assign(cases,{
 daniel:{name:'Daniel',initials:'DT',age:'31 years',context:'Recent contact',title:'Too early for reassurance.',subtitle:'Window-period testing and an indeterminate result.',time:'10–12 min',video:0,facts:[['Reason for visit','Recent household contact'],['Initial test','Negative IGRA shortly after exposure'],['Your role','Interpret timing and risk']],objectives:['Interpret a negative early test.','Distinguish indeterminate from negative.','Change the plan when symptoms arise.'],steps:[
 Q('The early result','Daniel is immunocompetent and well. His last household exposure was two weeks ago. His initial IGRA is negative.','Which interpretation best fits the timing?',['The negative result excludes infection from this exposure.','Infection may not yet be detectable; arrange follow-up testing under the contact pathway.','The result establishes that preventive treatment is unnecessary under all circumstances.'],[1],'An early negative result may precede a detectable immune response. Timing and host risk guide follow-up.','Do not apply a routine adult waiting plan to a highly vulnerable contact.','igra'),
 Q('Planning the next test','For this learning case, you are using the supplied international reference: repeat testing 8–10 weeks after the last exposure for an initially negative contact. The local appointment will be coordinated by the screening service.','Which date anchors this interval?',['The day of the GP consultation','The day the initial IGRA was reported','The last exposure to the infectious source'],[2],'The supplied interval is measured from the last exposure, not from the blood-result date.','Use the current local screening schedule in practice; do not silently relabel international timing as Singapore policy.','igra'),
 Q('An uninformative follow-up','At the follow-up test, the laboratory reports an indeterminate IGRA with an inadequate control response. Daniel remains well.','What is the appropriate next approach?',['Review clinical and laboratory context and arrange repeat or alternative testing if indicated.','Treat the result as negative because it is not positive.','Use the numeric antigen response alone and ignore the failed control.'],[0],'The controls help determine whether the result is interpretable. An indeterminate result does not provide a negative classification.','If disease is suspected, investigate it independently of the infection-test result.','igra'),
 Q('A new symptom changes the task','Before repeat testing, Daniel develops a persistent cough and weight loss.','What should take priority?',['Wait for the repeat IGRA before arranging imaging.','Evaluate for TB disease now and arrange appropriate escalation.','Offer routine preventive treatment because he is a contact.'],[1],'New symptoms change the clinical question. Disease evaluation should not wait for an immune-response test.','A screening pathway must allow a patient to move into the disease pathway.','diagnosis')
 ]},
 lim:{name:'Mr Lim',initials:'KL',age:'63 years',context:'Uncertain CXR finding',title:'The report says “old changes”.',subtitle:'Reconciling imaging before preventive treatment.',time:'10–12 min',video:1,facts:[['Reason for visit','Positive IGRA'],['Imaging','Apical changes, no comparison available'],['Your role','Resolve uncertainty before prevention']],objectives:['Avoid anchoring on radiology wording.','Use comparison information appropriately.','Proceed when the full assessment is reassuring.'],steps:[
 Q('A label is not a conclusion','Mr Lim has a positive IGRA and no reported symptoms. His CXR report describes apical scarring, likely old, with no comparison image available. Prior TB treatment history is unclear.','What is the next step?',['Start preventive treatment because the report says old.','Repeat IGRA to establish whether the scarring is inactive.','Clarify prior history and imaging, and assess whether further disease investigation is needed.'],[2],'The imaging label must be interpreted with clinical history and comparison information.','A negative or unchanged infection test would not determine the significance of the scar.','diagnosis'),
 Q('Retrieve information that matters','You can obtain prior records before deciding.','Select the information most useful to this assessment.',['Previous imaging and reports','History and documentation of prior TB treatment','A serial IGRA trend to measure disease activity','A focused symptom review and relevant examination'],[0,1,3],'Comparison imaging, treatment history and the clinical assessment help establish what the finding means.','Retrieve existing evidence before duplicating investigations.','diagnosis',true),
 Q('New evidence','A prior film shows the apical change was not present a year ago. Mr Lim now recalls recent appetite loss.','How should this change the plan?',['Defer prevention and evaluate for TB disease through the appropriate pathway.','Proceed with preventive treatment because there is no cough.','Consider disease excluded if a second IGRA is negative.'],[0],'A new radiographic finding and constitutional symptom require further disease evaluation.','Absence of cough does not exclude TB disease.','diagnosis'),
 Q('After specialist assessment','Following further assessment, the specialist team concludes there is no TB disease and documents that preventive care can proceed in general practice. Mr Lim has no difficult interaction or other treatment complexity.','What should the GP do next?',['Refer every preventive-care visit back to the specialist.','Review the documented conclusion and complete a shared regimen and monitoring decision.','Repeat the entire disease work-up automatically before discussing treatment.'],[1],'A documented, resolved evaluation enables the GP to continue uncomplicated care. Check that the clinical situation has not changed.','Appropriate specialist input should support continuity rather than unnecessary duplication.','overview')
 ]},
 siti:{name:'Siti',initials:'SN',age:'39 years',context:'Treatment preferences',title:'“I need a plan that fits my life.”',subtitle:'Risk communication and a decision to pause.',time:'10–12 min',video:4,facts:[['Assessment','TB infection without disease'],['Concern','Treatment burden and adverse effects'],['Your role','Shared decision-making']],objectives:['Elicit patient priorities.','Communicate risk without false precision.','Support an informed decision to defer.'],steps:[
 Q('Understand the concern','Siti has completed assessment for TB infection. She works shifts and cares for a parent. She says, “I do not think I can manage another thing.”','Which response best opens the conversation?',['“The regimen is short, so it should be manageable.”','“What part of the treatment or follow-up feels most difficult?”','“Let us start today and deal with any difficulty later.”'],[1],'An open question identifies the actual barrier. Shift work, access and caregiving may need different solutions.','Practical barriers should be explored rather than treated as unwillingness.'),
 Q('Explain prevention','Siti asks why treatment is offered when the assessment found no disease.','Which explanation is most accurate?',['It reduces the chance of future TB disease; the benefit and burden should be considered in her circumstances.','It prevents her from transmitting TB infection to others today.','It guarantees she will never develop TB disease.'],[0],'Preventive treatment aims to reduce future disease risk, not current transmission from TB infection.','Explain the intended benefit without promising certainty.'),
 Q('Making the plan workable','Siti says appointment timing is the main difficulty and asks what support is possible.','Select appropriate responses.',['Discuss practical appointment options available in the service','Agree a clear route for advice if symptoms develop','Promise that monitoring can be omitted because she is busy','Ask her to describe the plan back in her own words'],[0,1,3],'A feasible plan includes access, safety-netting and a check of understanding. Do not promise a service arrangement or omit needed monitoring without assessment.','Tailor the plan within actual clinical and service capability.','treatment',true),
 Q('An informed pause','After discussion, Siti wants time to consider treatment. She understands the potential benefit and has no symptoms of disease.','What is the best next plan?',['Record treatment failure.','Tell her future TB disease is inevitable.','Document her informed preference, provide safety-netting and agree a follow-up conversation.'],[2],'An informed pause is a legitimate decision. It requires documentation and an agreed next step.','Treatment uptake alone is not a measure of consultation quality.')
 ]},
 chen:{name:'Mr Chen',initials:'WC',age:'56 years',context:'During treatment',title:'The follow-up inbox.',subtitle:'Expected effects, liver tests and urgent symptoms.',time:'12–15 min',video:5,facts:[['Treatment','4R, following a completed assessment'],['Current task','Review messages and test results'],['Your role','Triage and act']],objectives:['Distinguish expected effects from symptoms requiring review.','Interpret laboratory results with context.','Escalate serious adverse reactions.'],steps:[
 Q('Orange urine','Mr Chen reports orange urine shortly after starting rifampicin. He feels entirely well, with no nausea, jaundice, abdominal pain or rash.','What is appropriate?',['Withhold treatment until urine colour returns to normal.','Explain the expected effect, confirm no concerning symptoms and reinforce warning signs.','Reduce the dose because the colour proves excessive drug exposure.'],[1],'Orange discolouration can be an expected rifampicin effect. It is distinct from dark urine accompanied by systemic symptoms.','Reassurance should include a check for symptoms that would change the advice.'),
 Q('An abnormal test','At a later review he feels well. ALT is 240 U/L; the laboratory upper limit is 40 U/L. For this case use the supplied CDC withholding reference: more than 5 times ULN without symptoms.','What should happen?',['Continue unchanged because there are no symptoms.','Reduce the dose by half without further assessment.','Withhold treatment and arrange clinical assessment of the abnormality and a follow-up plan.'],[2],'ALT is six times the laboratory upper limit, above the supplied asymptomatic withholding threshold. Assess other causes and the full clinical context.','Use the laboratory-specific ULN and approved local protocol; do not judge by the absolute number alone.'),
 Q('Symptoms before results','A different patient calls with new anorexia and jaundice before their first follow-up blood test.','Should advice wait for a laboratory threshold?',['No: advise withholding treatment and urgent assessment based on the symptoms.','Yes: continue until a test exceeds the threshold.','Use alternate-day treatment while waiting.'],[0],'Concerning symptoms warrant action before a result is available. Laboratory thresholds are not a reason to delay assessment.','A monitoring schedule cannot replace access to urgent advice.'),
 Q('A rash with warning features','Another patient reports fever, a widespread rash and painful mouth lesions while taking preventive treatment.','What is the next action?',['Continue and use a topical cream until routine review.','Stop treatment and arrange urgent medical assessment for a potentially severe reaction.','Change to another preventive regimen immediately without examination.'],[1],'Mucosal involvement and systemic features raise concern for a severe drug reaction. Urgent assessment is needed.','Do not advise unsupervised rechallenge after a serious reaction.')
 ]},
 priya:{name:'Priya',initials:'PR',age:'45 years',context:'Planned immunosuppression',title:'A decision with another team.',subtitle:'Complexity, timing and a focused handover.',time:'10–12 min',video:6,facts:[['Context','Biologic treatment is being planned'],['Infection test','Positive IGRA'],['Your role','Coordinate assessment and specialist advice']],objectives:['Recognise timing-sensitive complexity.','Send an actionable handover.','Maintain interim responsibility.'],steps:[
 Q('A time-sensitive referral','Priya’s rheumatologist plans biologic treatment. Screening shows a positive IGRA. Her disease-exclusion assessment is not complete.','What is the best next direction?',['Complete assessment for TB disease and coordinate the preventive plan and timing with NTBSC and rheumatology.','Use a fixed delay for biologic therapy without discussing the specific treatment.','Wait until immunosuppression starts before considering prevention.'],[0],'The risk, assessment, regimen and immunosuppression timing must be coordinated. No universal interval is supplied for this case.','Avoid inventing a single timing rule across different immunosuppressive treatments.','overview'),
 Q('A useful advice request','Priya is well and imaging has now been reported.','Select information to include in the request.',['Proposed immunosuppressive treatment and intended timing','Infection result, clinical assessment and imaging','Relevant medicines, comorbidity and baseline results','Only the positive IGRA; the specialist can reconstruct the rest'],[0,1,2],'An actionable request provides the clinical evidence and the actual timing question.','Shared care works better when the receiving team can identify the unresolved decision.','overview',true),
 Q('New respiratory symptoms','While awaiting advice Priya develops cough and weight loss.','How should the plan change?',['Keep the routine infection referral unchanged.','Start preventive treatment while awaiting the appointment.','Reassess promptly for TB disease and redirect to the disease pathway as appropriate.'],[2],'New symptoms change the clinical problem. Reconsider disease rather than continuing the original plan unchanged.','All preventive-care pathways need a route for emerging disease concern.','diagnosis'),
 Q('Who follows the result?','You have arranged further investigations and contacted the receiving team.','What completes your immediate plan?',['Assume all responsibility transferred with the telephone call.','Document who reviews each outstanding result, who contacts Priya and what symptoms require urgent care.','Ask Priya to interpret her portal results herself.'],[1],'Explicit result ownership and safety-netting are part of safe coordination.','A request sent is not the same as a completed clinical handover.','cda')
 ]},
 kumar:{name:'Kumar',initials:'SK',age:'48 years',context:'Treatment completion',title:'Four months later. Is treatment complete?',subtitle:'Reconcile doses and plan the next encounter.',time:'10–12 min',video:7,facts:[['Regimen','4R'],['Concern','An interruption during travel'],['Your role','Determine the documented outcome']],objectives:['Distinguish calendar duration from completion.','Handle interruption without unsafe catch-up.','Explain post-treatment testing.'],steps:[
 Q('The anniversary','Kumar started 4R four months ago. He reports taking no tablets for three weeks during travel, with several other missed doses.','What should happen before recording completion?',['Record complete because four months have elapsed.','Reconcile actual treatment against the regimen’s approved completion rules.','Repeat IGRA and record completion if it is negative.'],[1],'The doses and interruptions must be considered alongside the approved completion window.','Do not declare completion from the first-prescription date alone.'),
 Q('Catch-up advice','Kumar asks whether he should double the daily dose to make up for missed treatment.','What is appropriate?',['Agree because the cumulative dose will be the same.','Stop all follow-up because missed doses make treatment ineffective.','Advise against doubling; review symptoms and the interruption and agree a regimen-specific plan, with advice if needed.'],[2],'Do not use double dosing to compensate. The clinical review and completion policy determine whether to extend, restart or otherwise revise the plan.','Ask why treatment was interrupted so the revised plan is feasible.'),
 Q('A documented completion','After an agreed plan, the clinician confirms completion against the approved criteria. Kumar asks for a repeat IGRA to prove treatment worked.','What should you explain?',['IGRA may remain positive; it is not a test of cure. Provide the treatment record and future symptom advice.','A persistent positive result proves viable bacteria remain and requires repeat treatment.','A negative result guarantees there can be no future TB disease.'],[0],'An immune-response result is not a measure of preventive-treatment completion or cure.','Preserve records so later clinicians can interpret a previous positive test.'),
 Q('The treatment record','You prepare Kumar’s record.','Select the information that belongs in it.',['Original test and relevant imaging results','Regimen, dose, dates, interruptions and documented outcome','Future symptom advice and how to seek review','A guarantee that later symptoms cannot represent TB'],[0,1,2],'A useful record captures what was assessed and delivered, and what future symptoms should prompt review.','Previous treatment does not remove the need to assess new symptoms.','treatment',true)
 ]}
});
const caseOrder=['mei','daniel','rahman','lim','siti','anita','chen','priya','kumar'];
// Blueprint domain IDs are stable across revisions.
const domains={interpretation:'Foundations & test interpretation',disease:'Disease recognition & evaluation',prescribing:'Shared decisions & prescribing',monitoring:'Monitoring & completion',coordination:'Coordination & scope'};
const caseDomains={mei:'prescribing',daniel:'interpretation',rahman:'disease',lim:'disease',siti:'prescribing',anita:'prescribing',chen:'monitoring',priya:'coordination',kumar:'monitoring'};
const domainLessons={interpretation:['biology','testing'],disease:['disease','exclude'],prescribing:['decision','prescribe'],monitoring:['monitor','completion'],coordination:['complex']};
// New integrated assessment: ten scenarios, three decisions per scenario.
const examGroups=[
{label:'A screening result',domain:'interpretation',items:[
Q('Evidence of infection','A 29-year-old healthcare worker, vaccinated with BCG, has a positive IGRA after contact screening. No clinical assessment has been completed.','Which statement is supported?',['BCG explains the positive IGRA.','The result supports infection but does not establish disease status.','The result establishes infectious pulmonary TB.','The result dates infection to the most recent contact.'],[1],'IGRA is not affected by BCG and does not establish disease status or infection timing.','Use the result to guide assessment, not to replace it.','igra'),
Q('Choosing evidence','The same patient is worried about transmitting TB.','Which evidence is needed to address the clinical question?',['A second IGRA value alone','Whether the TST is also positive','An infection-test conversion threshold','Clinical assessment for disease, with imaging and further investigation where indicated'],[3],'Infectiousness cannot be read from the infection test. Assess disease and the relevant clinical circumstances.','Interpret infectiousness separately from the infection–disease distinction.','overview'),
Q('After assessment','The completed assessment finds no TB disease. The patient asks whether a separate bedroom is necessary solely because the IGRA is positive.','Which advice fits the conclusion?',['TB infection alone is not infectious; separate sleeping is not required on that basis.','Separation is required until the IGRA is negative.','Separation is required throughout all preventive treatment.','The advice depends only on the numerical IGRA level.'],[0],'TB infection without disease is not infectious.','Explain the preventive purpose of treatment.','overview')
]},
{label:'A recent exposure',domain:'interpretation',items:[
Q('The window period','An otherwise well, immunocompetent adult is tested two weeks after last exposure and has a negative IGRA.','What is the most appropriate interpretation?',['Recent infection is excluded.','The result indicates drug resistance.','The result may be too early to exclude infection; follow the contact-screening pathway.','The patient needs immediate treatment for TB disease.'],[2],'An immune response may not yet be detectable after recent exposure.','Timing matters.','igra'),
Q('An indeterminate result','At follow-up, an IGRA is indeterminate. There are no symptoms of disease.','Which approach is appropriate?',['Review possible causes and arrange repeat or alternative testing if still indicated.','Classify the test as negative.','Classify the test as positive regardless of controls.','Infer infectiousness from the nil-tube value.'],[0],'An indeterminate result is uninformative and needs contextual assessment.','Controls affect interpretability.','igra'),
Q('Symptoms change the question','While awaiting clarification, the patient develops cough and night sweats.','What should take priority?',['Wait until an infection test is clearly positive.','Repeat infection testing every week before imaging.','Begin preventive rifampicin without further assessment.','Evaluate for TB disease without waiting for repeat infection testing.'],[3],'Disease investigation is driven by the clinical presentation.','Do not let a screening pathway delay disease evaluation.','diagnosis')
]},
{label:'A concerning radiograph',domain:'disease',items:[
Q('Clinical suspicion','A 61-year-old has weight loss and an upper-zone cavity. The IGRA is negative.','Which direction is appropriate?',['TB disease is excluded.','Repeat IGRA before any referral.','Arrange prompt TB disease evaluation despite the negative IGRA.','Treat as uncomplicated TB infection.'],[2],'A negative immune-response test does not exclude TB disease.','Concerning clinical evidence needs action.','diagnosis'),
Q('Initial microbiology','Initial smear microscopy is negative. The patient remains symptomatic.','Which interpretation is most appropriate?',['A negative smear establishes non-infectious TB infection.','Negative smear does not exclude disease; continue the indicated work-up.','Culture is only useful after a positive smear.','Repeat IGRA is the next microbiological test.'],[1],'Smear microscopy has limited sensitivity. Molecular testing and culture offer complementary information.','One negative test does not settle a high-suspicion presentation.','diagnosis'),
Q('Clinic precautions','The stable patient is still in the clinic awaiting care arrangements.','Select appropriate actions.',['Provide suitable source control and reduce exposure to others','Arrange collection of indicated specimens in a suitable setting','Ask for vigorous sputum induction in the shared waiting area','Coordinate prompt referral without waiting for all results'],[0,1,3],'Exposure reduction, safe collection and timely coordination belong together.','Do not delay referral while assembling a perfect set of results.','cda',true)
]},
{label:'Before prevention',domain:'disease',items:[
Q('An incomplete assessment','A well person has a positive IGRA, but imaging and relevant medical history are not yet available.','What is appropriate?',['Start treatment because they feel well.','Repeat IGRA to replace the missing assessment.','Assume a normal examination would exclude disease.','Complete the appropriate assessment before deciding on preventive treatment.'],[3],'Feeling well does not complete disease exclusion.','Assess the missing prerequisites.','overview'),
Q('A reassuring assessment','The patient is immunocompetent and remains asymptomatic. Examination and CXR are normal; there is no prior treatment or regimen complexity.','What should follow?',['GP-led discussion of preventive treatment and a suitable plan','Automatic transfer of all care to NTBSC','Routine sputum induction for every asymptomatic person','Repeat IGRA to measure cure before treatment'],[0],'This is a suitable setting for uncomplicated preventive care in general practice under the agreed pathway.','Appropriate retention in GP care is a positive outcome.','overview'),
Q('A new finding','Before medication is started, the patient reports a new persistent cough.','What should happen?',['Proceed because the earlier assessment remains conclusive.','Ignore symptoms until the next infection test.','Reassess for disease and reconsider whether it is safe to proceed.','Reduce the planned preventive dose.'],[2],'A new symptom can change the evidence on which the previous decision rested.','Disease exclusion is not permanent.','diagnosis')
]},
{label:'A shared prescription',domain:'prescribing',items:[
Q('The patient’s concern','A suitable patient is uncertain about treatment because of shift work.','Which response best supports a decision?',['Assure them there can be no significant adverse effects.','Explore the practical concern and discuss a feasible plan alongside benefits and harms.','Record non-adherence before a decision is made.','Use household isolation as an incentive to accept treatment.'],[1],'Explore the actual barrier and explain benefit and burden.','Respect the patient’s circumstances.'),
Q('A dose with a reference','A 75-kg adult has chosen 4R after a completed suitability assessment. Supplied reference: rifampicin 10 mg/kg daily, maximum 600 mg.','What is the appropriate daily dose?',['450 mg','750 mg','300 mg','600 mg'],[3],'The calculated weight-based amount exceeds the maximum, so the daily dose is 600 mg.','Apply both the weight calculation and dose cap.'),
Q('The prescription record','You are documenting the plan.','Select the necessary elements.',['Drug, dose, route and frequency','Intended duration and start date','A repeat IGRA as the primary adherence measure','Counselling, monitoring and access to advice'],[0,1,3],'The prescription and care plan require complete treatment details and follow-up arrangements.','A test result is not an adherence record.','treatment',true)
]},
{label:'A medication change',domain:'prescribing',items:[
Q('A new prescription','Before starting 4R, the patient brings a new medicine prescribed elsewhere.','What must happen?',['Reconcile it and check its specific interaction with the planned regimen.','Ignore it if it was prescribed by a specialist.','Separate all tablets by four hours.','Start and check only if symptoms occur.'],[0],'The new medicine may change regimen suitability.','Medication review is not a one-off event.'),
Q('A significant interaction','The reference advises avoiding the combination. The other medicine is clinically important.','What is appropriate?',['Stop the other medicine without coordination.','Use half-dose rifampicin without advice.','Defer the conflicting regimen and coordinate a suitable alternative or specialist plan.','Proceed because preventive treatment does not cause interactions.'],[2],'Coordinate the treatment plan rather than improvising an unsafe adjustment.','One unsuitable regimen does not make all prevention impossible.'),
Q('Stopping rifampicin','A co-prescribed medicine had been adjusted under specialist advice during rifampicin treatment. Rifampicin is now ending.','What should be reviewed?',['Only the infection-test result','Whether the other medicine needs reassessment as the interaction changes after rifampicin stops','Whether every medicine must stop permanently','Whether the patient can restart any previous dose without advice'],[1],'Stopping an interacting drug can change medication requirements.','Include cessation in the interaction plan.')
]},
{label:'An adverse-effect call',domain:'monitoring',items:[
Q('Concerning symptoms','A patient on preventive treatment reports persistent nausea, anorexia and jaundice.','What is the appropriate action?',['Continue until routine review.','Take half the dose and observe.','Repeat IGRA before deciding.','Withhold treatment and arrange urgent clinical assessment.'],[3],'Potential hepatitis warrants prompt assessment.','Do not wait for scheduled monitoring.'),
Q('Use the supplied threshold','A separate asymptomatic patient has ALT 300 U/L with ULN 50 U/L. The supplied reference advises withholding above 5 times ULN without symptoms.','How should this result be managed?',['Continue because there are no symptoms.','Withhold and assess; the value is six times ULN.','Continue until ALT reaches ten times ULN.','Adjust based on the IGRA response.'],[1],'The result exceeds the supplied asymptomatic threshold.','Interpret the ratio to the laboratory ULN and the clinical context.'),
Q('Severe reaction','A patient develops fever, widespread rash and mucosal lesions.','What should be advised?',['Stop treatment and arrange urgent assessment.','Continue with antihistamines alone until next month.','Change regimen immediately without assessment.','Take the next dose to confirm causation.'],[0],'Systemic and mucosal features can indicate a serious reaction.','Unsupervised rechallenge is inappropriate.')
]},
{label:'A treatment record',domain:'monitoring',items:[
Q('An interruption','Four calendar months have passed since 4R was prescribed, but there was a lengthy interruption.','What establishes completion?',['The calendar anniversary alone','Whether IGRA is lower','Treatment received reconciled against approved regimen-specific criteria','Whether the patient has symptoms today'],[2],'Completion requires a treatment record and the correct regimen criteria.','Elapsed time alone is not enough.'),
Q('The repeat-test request','After documented completion, a patient asks for IGRA to demonstrate cure.','What is appropriate?',['Order it and repeat treatment if positive.','Advise that IGRA is not a test of cure and may remain positive.','Promise the result must now be negative.','Use the numerical change to calculate protection.'],[1],'IGRA is an immune-response test, not a treatment-outcome test.','Provide documentation instead.'),
Q('New symptoms after treatment','A previously treated person develops cough and weight loss.','What should happen?',['Exclude TB from the differential because treatment was completed.','Repeat preventive treatment without assessment.','Judge the symptoms only by the last IGRA.','Evaluate the symptoms for possible TB disease and other causes.'],[3],'Previous treatment does not remove the need to evaluate new symptoms.','Safety-netting extends beyond the final dose.')
]},
{label:'Coordinating care',domain:'coordination',items:[
Q('Notify and refer','You suspect pulmonary TB and have referred the patient to NTBCC. Culture is pending.','Which statement is correct?',['Referral replaces the notification duty.','Notification must always wait for culture.','Notification of suspected disease is separate from referral; use the current Singapore process.','Only the laboratory can notify TB.'],[2],'Singapore requires notification of suspected or confirmed cases.','Referral and notification serve different purposes.','cda'),
Q('A resistant source','A contact’s source isolate is reported as rifampicin-resistant. TB disease has been excluded in the contact.','Which is the appropriate direction?',['Seek NTBSC specialist assessment of preventive options.','Automatically use 4R unchanged.','Assume there is no possible preventive approach.','Use an IGRA level to choose the antibiotic.'],[0],'Preventive options require source-specific expert assessment and local implementation.','Do not extrapolate a drug-susceptible regimen.','who'),
Q('An outstanding result','A referral is accepted but a requested test is still pending.','What is needed?',['No further action because the referral was accepted.','Explicit agreement on result review, patient contact and interim safety-netting.','Ask the patient to interpret the result.','Repeat the referral without communicating the pending test.'],[1],'Clear ownership prevents results being lost between services.','Sending and closing the loop are different actions.','cda')
]},
{label:'Deciding within scope',domain:'disease',items:[
Q('Acute deterioration','A patient with suspected pulmonary TB becomes breathless at rest and hypoxic in your clinic.','What takes priority?',['Routine referral at the next available appointment','Repeating IGRA','Starting preventive treatment','Emergency assessment with appropriate precautions'],[3],'Acute instability requires emergency care rather than routine outpatient processing.','Urgency is determined by the patient’s condition.','diagnosis'),
Q('Disease uncertainty','A symptomatic patient has abnormal imaging and one negative molecular sputum test.','What is the safe interpretation?',['The test establishes TB infection without disease.','No further evaluation is needed.','Disease remains possible; continue the indicated evaluation.','IGRA can now determine infectiousness.'],[2],'A negative test may not exclude disease when suspicion remains.','Integrate rather than substitute evidence.','diagnosis'),
Q('An informed decision','A suitable patient declines prevention after understanding the benefits and harms.','What is appropriate?',['Respect and document the decision, provide symptom advice and agree local follow-up.','Record successful completion.','Tell them disease is inevitable.','Offer no further advice because they declined.'],[0],'Good care respects informed choice and retains safety-netting.','Uptake is not the only outcome of a good consultation.')
]}
];
challenge.steps=examGroups.flatMap((g,gi)=>g.items.map((q,qi)=>({...q,id:`SUM-${String(gi+1).padStart(2,'0')}-${qi+1}`,group:g.label,groupIndex:gi,domain:gi===9&&qi===2?'prescribing':g.domain,safety:['2:0','3:0','3:2','5:1','6:0','6:2','9:0','9:1'].includes(`${gi}:${qi}`)})));
challenge.title='An integrated clinical assessment.';
const clinicalReviewItems=[
['Local prescribing scope','Confirm the adults and regimens GPs should manage independently, and criteria for advice, shared care or referral.','Prescribing; all patient journeys'],
['Baseline and follow-up tests','Approve the Singapore baseline policy, hepatic-risk criteria, follow-up intervals and remote-review arrangements.','Monitoring lesson and case feedback'],
['Notification workflow','Confirm the current submission route, deadline, trigger and operational responsibility. The course teaches suspected or confirmed disease notification without inventing a local deadline.','Disease lesson; referral assessments'],
['Treatment completion','Approve dose-count, maximum-duration and interruption rules for each locally used regimen.','Completion lesson and Kumar journey'],
['Adverse effects','Reconcile local thresholds and escalation arrangements with international symptom and laboratory guidance.','Monitoring; safety decisions'],
['Singapore guideline reconciliation','Full-text comparison with the 2024 Singapore guideline remains outstanding because the public full text was not retrievable during this build.','Reference mapping and clinical sign-off'],
['Formal standard setting','Convene a GP/TB/education panel for modified Angoff review, pilot items and approve remediation rules before making pass/fail claims.','Final assessment'],
['Videos and imaging','Record approved explainers with captions and transcripts. Add permission-cleared clinical imaging with expert annotation. Current cases use text reports.','Media assets']
];
