/* Clinical lead clarifications, September 2026. Public supplement: Appendix S2. */
const careChoice='Tuberculum builds GP competence and confidence to offer TB infection care when they choose to do so. NTBSC provides both uncomplicated and complex TB infection care, including assessment, counselling, treatment and follow-up. GP-led care, NTBSC-led care and agreed shared care are available according to patient preference, clinical need and service arrangements. Contacts are not automatically assigned to general practice.';
const hepaticPolicy='Higher hepatic risk includes elevated baseline ALT/AST, age ≥60 years, hepatitis B or C, other chronic liver disease, alcohol consumption, pregnancy, HIV, and statins or other potentially hepatotoxic medicines. Obtain baseline ALT/AST. Plan repeat ALT/AST at 4–6 weeks and thereafter at 4–6-weekly intervals while indicated; monitoring blood tests may be withheld at clinician discretion after individual assessment. This discretion does not remove the need to act on symptoms or known abnormal results.';
const baselinePolicy='At baseline ALT/AST above 2× the laboratory upper limit of normal (ULN), defer starting preventive treatment and investigate the cause. At exactly 2× ULN, treatment may be continued after clinical assessment, with repeat ALT/AST in 1–2 weeks. Mild elevations below 2× ULN do not automatically preclude treatment. Results need not fully normalise before another trial, but the cause, trend, symptoms and suitability must be reassessed; seek focused NTBSC advice when uncertain. This is not permission for unsupervised rechallenge after drug-induced liver injury.';
const stoppingPolicy='Under this local care policy, stop preventive treatment if ALT or AST exceeds 3× ULN, including when there are no symptoms. Assess the patient, obtain appropriate liver tests including bilirubin, investigate other causes and agree escalation and repeat testing. Stable patients may have repeat tests in 1–2 weeks; jaundice, acute illness or deterioration requires urgent assessment rather than waiting for that interval. Concerning symptoms require withholding treatment and prompt assessment even below the numerical threshold.';
const interruptionPolicy='First establish why treatment stopped, the doses taken and whether new symptoms or adverse effects require assessment. For 4R and 6H, Appendix S2 advises resuming after an interruption of less than two weeks and adding the missed days to the treatment duration. For interruptions of at least two weeks: after at least 80% of expected doses, continue and complete the remaining treatment; after less than 80%, continue if completion remains possible within the planned duration plus 33% additional time, otherwise consider restarting the full course. Taking at least 80% does not itself mean treatment is complete: complete the remaining treatment. Inclusion of exactly 80% in this branch is the course clinical lead’s local clarification of the boundary omitted from Table S2. Toxicity-related interruptions need a separate clinical plan before restarting. Do not double doses.';
const surveillancePolicy='After completion, provide a treatment record and symptom safety-netting. CXR surveillance may form part of an individual contact follow-up plan, including when prevention is declined or incomplete. There is no universal surveillance schedule in this course. Agree whether surveillance is needed, its interval and duration, and whether the GP or NTBSC will arrange imaging, review results and contact the patient. New symptoms need assessment without waiting for scheduled imaging.';
teach('monitor',1,'Risk-based monitoring with clinical discretion',hepaticPolicy);
teach('monitor',3,'Local stopping and reassessment policy',stoppingPolicy);
lessonById('monitor').sections.push(['Baseline abnormalities and another treatment trial',baselinePolicy]);
lessonById('monitor').visual=graphic('Monitor the patient and the results',`<div class="graphic-grid">${tile('Before treatment','Baseline ALT/AST; assess hepatic risk and treatment suitability.')}${tile('During treatment','Higher risk: plan 4–6-weekly bloods. Clinicians may withhold routine monitoring bloods after individual assessment.')}${tile('Act on new evidence','Stop if ALT or AST >3× ULN, even without symptoms. Symptoms may require stopping and assessment below this threshold.')}</div>`);
lessonById('monitor').table.rows.push(['ALT or AST >3× ULN, with or without symptoms','Stop treatment; assess, investigate and arrange repeat tests/escalation'],['ALT/AST exactly 2× ULN','May continue after assessment; repeat in 1–2 weeks']);
teach('complex',0,'Choose the setting and support that fit the patient',careChoice+' Drug-specific contraindications still apply. Complexity may call for focused advice, shared care or referral, without necessarily transferring all care.');
teach('completion',1,'Apply the regimen-specific interruption guidance',interruptionPolicy);
teach('completion',4,'Agree any surveillance plan explicitly',surveillancePolicy);
lessonById('completion').visual=graphic('A gap in treatment: four questions',`<div class="graphic-grid">${tile('Why did treatment stop?','Resolve symptoms, toxicity and practical barriers first.')}${tile('How long was the interruption?','Distinguish less than two weeks from at least two weeks.')}${tile('What treatment remains?','Check doses taken and the applicable completion window; continue remaining doses or consider restarting as indicated.')}</div><p>For 4R and 6H, use Appendix S2. Do not equate taking at least 80% of doses with completion.</p>`);
const labItem=challenge.steps.find(q=>q.id==='SUM-07-2');
labItem.text='A separate asymptomatic patient taking preventive treatment has ALT 180 U/L with ULN 50 U/L. Supplied local policy: stop treatment when ALT or AST exceeds 3× ULN, even without symptoms.';
labItem.options[1]='Stop and assess; ALT is 3.6× ULN and exceeds the local threshold.';
labItem.why='The local stopping threshold is exceeded despite the absence of symptoms. Stop treatment and assess the cause, clinical severity and follow-up needs.';
labItem.transfer='Do not substitute an international asymptomatic threshold for the local policy supplied in this case.';
Object.assign(cases.chen.steps[1],{text:'At a later review he feels well. ALT is 140 U/L; ULN is 40 U/L. Supplied local policy: stop preventive treatment when ALT or AST exceeds 3× ULN, including without symptoms.',why:'ALT is 3.5× ULN, exceeding the local stopping threshold. Stop treatment, assess the clinical context and other causes, and arrange repeat tests and escalation as indicated.'});
const gapItem=challenge.steps.find(q=>q.id==='SUM-08-1');
Object.assign(gapItem,{text:'A patient taking 4R had a three-week interruption unrelated to toxicity. They remain well after reassessment, have taken 60% of expected doses, and can complete the remainder within the planned duration plus 33% additional time. Supplied Appendix S2 guidance: with an interruption ≥2 weeks and <80% of doses taken, continue if completion remains possible within that window; otherwise consider restarting.',question:'Which plan follows the supplied guidance?',options:['Restart the entire course solely because the gap exceeded two weeks','Record treatment complete because more than half the doses were taken','Continue and complete the remaining treatment, addressing the reason for interruption','Double the daily dose until the original calendar end date'],answer:[2],why:'The patient can complete the remaining treatment within the stated window. Continue the course and address the interruption; neither automatic restarting nor double dosing is indicated.',transfer:'Apply interruption duration, doses taken and remaining completion time together.'});
cases.kumar.steps[1].why+=' '+interruptionPolicy;
// Keeping care with a GP is an option, not a mandatory service destination.
challenge.steps.find(q=>q.id==='SUM-04-2').options[0]='Discuss preventive treatment and agree a GP-led, NTBSC-led or shared-care plan';
challenge.steps.find(q=>q.id==='SUM-04-2').why='Uncomplicated care can be offered by a willing GP or by NTBSC. Agree a suitable plan with the patient; complexity is not a prerequisite for NTBSC care.';
challenge.steps.find(q=>q.id==='SUM-04-2').transfer='Build capability and patient choice without mandating the care setting.';
const referenceBeforePolicy=reference;
reference=function(){return referenceBeforePolicy()+`<section class="card"><h2>Choosing where TB infection care happens</h2><p>${careChoice}</p></section><section class="card"><h2>Local hepatic monitoring and stopping policy</h2><p>${hepaticPolicy}</p><p>${baselinePolicy}</p><p>${stoppingPolicy}</p><p class="small">These local operational instructions have been specified by the course clinical lead. International references do not establish this local policy.</p></section><section class="card"><h2>4R and 6H treatment interruptions</h2><p>${interruptionPolicy}</p><p>Public source: Singapore TB clinical management guidelines 2024, Supplementary Materials, Appendix S2, Table S2 (p.10).</p></section><section class="card"><h2>Contact follow-up</h2><p>${surveillancePolicy}</p></section>`;};
// Align available narration with the taught clinical policy; recording remains a placeholder.
for(const v of videos){if(v.transcript)for(const slide of v.transcript){if(slide.title==='Separate visits from blood tests')slide.script=hepaticPolicy;if(slide.title==='Resolve the interruption before closing care')slide.script=interruptionPolicy;}}
videos[6].message=careChoice;
refs.local='#reference';
labItem.ref='local';cases.chen.steps[1].ref='local';lessonById('monitor').ref='local';
gapItem.ref='sg';cases.kumar.steps[1].ref='sg';lessonById('completion').ref='sg';
for(const v of videos){if(v.transcript)for(const slide of v.transcript){if(slide.script.includes('five times without symptoms'))slide.script=stoppingPolicy;if(slide.title==='Know your scope'){slide.script=careChoice+' GP prescribing in this course covers adult 4R and 6H after disease exclusion. Possible TB disease follows the NTBCC pathway; resistant-source contacts require specialist assessment.';slide.screen='TB infection: GP, NTBSC or shared care\nGP prescribing: adult 4R and 6H\nPossible TB disease: NTBCC';}if(slide.title==='Choose the level of support')slide.script=careChoice;}}

// Confirmed pyridoxine wording; the dose range is retained for individual assessment.
const pyridoxinePolicy='For adults receiving isoniazid, prescribe pyridoxine 10 mg orally daily routinely. Use 25–50 mg orally daily for patients with higher-risk features: older age, pregnancy or breastfeeding, malnutrition, alcohol use disorder, chronic liver disease, HIV, renal failure or diabetes. Select the dose within that range according to individual clinical assessment.';
lessonById('prescribe').sections[4][1]='Record drug, dose, oral route, daily frequency, intended duration and start date. Include administration, missed-dose advice, adverse-symptom advice and monitoring. '+pyridoxinePolicy;
lessonById('prescribe').table.rows.find(r=>r[0]==='6H')[2]='Hepatotoxicity and neuropathy risk. Pyridoxine: 10 mg/day routinely; 25–50 mg/day with higher-risk features.';
for(const v of videos){if(v.transcript)for(const slide of v.transcript){if(slide.title==='Make the plan complete')slide.script+=' '+pyridoxinePolicy;}}
const referenceBeforePyridoxine=reference;
reference=function(){return referenceBeforePyridoxine()+`<section class="card"><h2>Pyridoxine with isoniazid</h2><p>${pyridoxinePolicy}</p><p class="small">Course local prescribing policy.</p></section>`;};
