/* Educator review release 2.1: agreed GP scope and reviewable clinical visuals. */
refs.sg='https://annals.edu.sg/wp-content/uploads/2024/04/Annals-V53N3-March2024.pdf#page=48';
const lessonById=id=>lessonData.find(l=>l.id===id);
function teach(id,index,title,text){lessonById(id).sections[index]=[title,text];}
const graphic=(title,body)=>`<section class="clinical-graphic" aria-label="${title}"><div class="eyebrow">CLINICAL MAP</div><h2>${title}</h2>${body}</section>`;
const tile=(title,text)=>`<article class="graphic-tile"><h3>${title}</h3><p>${text}</p></article>`;
const naturalGraphic=graphic('TB infection and TB disease',`<div class="graphic-pair">${tile('TB infection','Infection without evidence of TB disease after appropriate assessment. Preventive treatment reduces the risk of future disease.')}${tile('TB disease','Disease caused by M. tuberculosis, in the lungs or elsewhere. Symptoms may be absent or atypical. Disease treatment requires a different pathway.')}</div><p class="graphic-bridge">Progression can occur, but is not inevitable. Recent infection and impaired immunity can increase risk.</p><div class="graphic-separate"><h3>A separate question: infectiousness</h3><p>TB infection alone is not infectious. With TB disease, assess the site and clinical circumstances. Pulmonary and laryngeal disease are the principal transmission concern. IGRA and TST do not determine infectiousness.</p></div>`);
const careGraphic=graphic('Choose the next care pathway',`<div class="graphic-gate"><strong>Before preventive treatment</strong><p>Clinical assessment and CXR must precede treatment. Investigate unresolved symptoms or findings.</p></div><div class="graphic-grid">${tile('Possible TB disease → NTBCC','Defer preventive treatment. Arrange evaluation, appropriate precautions and notification when indicated. If sputum investigations are needed and unavailable in the practice, refer.')}${tile('Uncomplicated TB infection → GP','Discuss preferences, review suitability and prescribe 4R or 6H when appropriate. Agree monitoring and access to advice.')}${tile('Complex TB infection → agreed shared care','Counsel, identify the specific difficulty and seek NTBSC advice or referral as required. Agree prescribing, monitoring and escalation responsibilities.')}</div><p class="graphic-bridge"><strong>MDR contact:</strong> mandatory specialist assessment; do not independently select routine 4R or 6H. Rifampicin-resistant source information also requires specialist assessment. Acute instability requires emergency care.</p>`);
const testGraphic=graphic('What an infection test can tell you',`<div class="graphic-pair">${tile('IGRA / TST can support','Evidence of an immune response compatible with infection, interpreted with timing, immune status and test quality.')}${tile('IGRA / TST cannot independently establish','TB disease versus TB infection without disease; exclusion of TB disease; infectiousness; preventive-treatment cure.')}</div><div class="graphic-grid">${tile('Positive','Assess for disease before preventive care.')}${tile('Negative','Consider early testing and immune status. Investigate concerning symptoms regardless.')}${tile('Indeterminate','Uninformative; review context and arrange appropriate repeat or alternative testing.')}</div>`);
const monitorGraphic=graphic('Monitoring has three parts',`<div class="graphic-grid">${tile('Before the first dose','Complete disease exclusion and medication review. Obtain baseline ALT and AST under this course’s local care model.')}${tile('Scheduled review','Review symptoms, actual doses and new medicines. Use 4–6 weekly follow-up; repeat ALT/AST 4–6 weekly when hepatic risk is high.')}${tile('Between appointments','Persistent nausea, anorexia, jaundice or systemic rash needs prompt assessment. Do not wait for the booked visit.')}</div><p class="small">Clinical review and blood testing are separate decisions. Longer clinical intervals may suit adherent patients at low adverse-event risk. The delivery model need not be nurse-led.</p>`);
const cxrGallery=`<section class="clinical-graphic"><div class="eyebrow">ILLUSTRATED RADIOLOGY DISCUSSION</div><h2>Read the report. Decide the next step.</h2><figure><a href="assets/cxr-illustrations.png" target="_blank" rel="noopener"><img class="cxr-sheet" src="assets/cxr-illustrations.png" width="1222" height="1287" loading="lazy" alt="Four synthetic CXR concepts: clear lung fields, upper-zone opacity, apical changes and a pleural abnormality. These are illustrative and awaiting expert review."></a><figcaption>Synthetic illustrations, not patient radiographs. Expert radiology review is pending. These images are not diagnostic reference standards and are not used for summative image scoring. Open the image to enlarge it.</figcaption></figure><p>Use the supplied scenario and report below. Pause to decide whether preventive care can proceed, further information is needed, or disease evaluation takes priority.</p><details><summary>A · Well adult; report: no radiographic abnormality</summary><p>Complete the remaining disease-exclusion and treatment-suitability assessment. A normal CXR alone does not exclude every form of TB disease; symptoms and immune status still matter.</p></details><details><summary>B · Weight loss; report: upper-zone cavity and opacity</summary><p>Defer preventive treatment and arrange prompt NTBCC evaluation. Coordinate sputum investigations through a suitable service, with appropriate precautions. This appearance is not specific for TB.</p></details><details><summary>C · No symptoms; report: apical changes, chronicity uncertain</summary><p>Retrieve comparison films and prior treatment history. Resolve uncertainty before preventive treatment; refer if sputum investigations or further disease evaluation are indicated. Appearance alone cannot establish inactivity.</p></details><details><summary>D · Breathlessness; report: unilateral pleural effusion</summary><p>Assess urgency and investigate the cause, including TB where appropriate. An effusion does not itself establish TB or infectiousness. Acute respiratory compromise needs emergency care.</p></details></section>`;
lessonById('biology').title='TB infection and TB disease';
lessonById('biology').lead='Understand the clinical distinction, then consider infectiousness separately.';
lessonById('biology').objective='Explain the distinction between TB infection and TB disease, and assess infectiousness as a separate clinical question.';
lessonById('biology').visual=naturalGraphic;
lessonById('biology').table={headers:['Clinical assessment','Evidence'],rows:[['Evidence compatible with infection','IGRA/TST in context'],['Assess for TB disease','History, examination, CXR and additional investigations when indicated']]};
lessonById('testing').visual=testGraphic;
lessonById('exclude').visual=careGraphic;
lessonById('disease').visual=cxrGallery;
lessonById('complex').visual=careGraphic;
lessonById('monitor').visual=monitorGraphic;
teach('exclude',0,'CXR before preventive treatment','Complete a symptom review, relevant history, examination and CXR before preventive treatment. Retrieve previous TB treatment and imaging records where relevant. CXR is a prerequisite in this course’s Singapore care model, not a replacement for clinical assessment.');
teach('disease',3,'Act while arranging the next step','For possible infectious pulmonary disease, provide appropriate source control and reduce exposure to others. Most GP practices cannot arrange sputum AFB investigations. If an abnormal CXR requires sputum investigation, refer through NTBCC for evaluation and safe specimen collection; do not delay referral to obtain tests unavailable in the practice. Do not induce sputum in a shared consultation area. Acute instability requires emergency care.');
teach('disease',4,'Notification is separate from referral','Notify diagnosed TB disease, including presumptive and confirmed disease, through CDLENS. CDA public guidance also states suspected or confirmed TB is notifiable. The proposed distinction for referral solely to investigate a possibility, without a presumptive diagnosis, remains under programme review; this course does not teach a blanket exemption from notification. Clarify the duty promptly using the current official process and document responsibility.');
teach('prescribe',1,'The two regimens within GP scope','This course covers 4R and 6H for uncomplicated adult TB infection. If rifampicin is unsuitable, assess whether six months of daily isoniazid (6H) is appropriate: review source susceptibility, liver risk, interactions and the patient’s ability to complete treatment. A contraindication to one medicine is not automatically a contraindication to all preventive care. Other regimens are outside this course’s prescribing scope.');
teach('prescribe',4,'Complete the prescribing task','Record drug, dose, oral route, daily frequency, intended duration and start date. Include administration, missed-dose advice, adverse-symptom advice and monitoring. Singapore guidance recommends pyridoxine for adults receiving isoniazid; the programme’s chosen dose remains to be confirmed before it becomes a scored prescription requirement.');
lessonById('prescribe').visual=graphic('Two regimens in GP scope',`<div class="graphic-pair">${tile('4R · four months','Rifampicin daily: 10 mg/kg, maximum 600 mg. Review all medicines and source susceptibility. Plan for interactions both when starting and stopping.')}${tile('6H · six months','Isoniazid daily: 5 mg/kg, maximum 300 mg. Review hepatic risk, interactions and source susceptibility. Include pyridoxine and neuropathy counselling.')}</div><p class="graphic-bridge">Both require prior disease exclusion, informed choice and an agreed monitoring plan. Select for the individual; seek focused advice if complexity remains.</p>`);
teach('monitor',1,'Plan clinical and laboratory review separately','The Singapore guideline allows clinical follow-up at 4–6 week intervals, with longer intervals for adherent patients at low adverse-event risk. This course’s agreed local model obtains baseline ALT and AST and repeats these 4–6 weekly for patients at high hepatic risk. The guideline permits baseline testing; the routine baseline requirement is the course care model. Exact hepatic-risk criteria remain for clinical approval. Symptoms require assessment between visits, with further liver testing as indicated. CDC monthly review is an international alternative, not the Singapore delivery model.');
teach('complex',0,'Complexity calls for judgement and support','Uncomplicated adult TB infection can be managed by GPs with 4R or 6H. Liver disease, major interactions and uncertain prior treatment call for individual assessment and focused advice, shared care or referral as required. Drug-specific contraindications still apply. Complexity alone does not require permanent transfer of all care.');
teach('complex',2,'Special populations and resistant-source contacts','For pregnancy, children and people living with HIV, treatment should be initiated by or in close consultation with the relevant specialist. The GP may counsel and provide agreed shared care. MDR contacts require specialist assessment through NTBSC; this is a boundary on independent GP management, not a statement that no preventive treatment is possible. Rifampicin-resistant source information also needs specialist assessment.');
teach('complex',4,'Agree responsibilities explicitly','With the patient and specialist, agree who selects and prescribes treatment, who reviews symptoms and blood results, and who handles adverse effects, missed visits and completion. The GP can retain continuity and deliver agreed elements of care. Refer to NTBSC when required for complex TB infection; concern about TB disease follows NTBCC.');
teach('completion',4,'After treatment or a decision to decline','Routine treatment follow-up can end after completion, with a treatment record and symptom safety-netting. Contacts may have six-monthly CXR surveillance under an individual screening-service plan. Confirm who arranges it and for how long; do not apply a universal schedule to everyone who declines or does not complete treatment. The programme’s surveillance eligibility and duration remain for clinical review.');
// Update clinical decisions as well as teaching; preserve stable item IDs and scoring metadata.
cases.rahman.steps[1].options[3]='Coordinate indicated sputum microbiology through NTBCC or another suitable service when unavailable in the GP practice';
cases.rahman.steps[2].text='The receiving clinician documents a presumptive diagnosis of pulmonary TB and plans disease treatment. Culture is pending. You are preparing the handover and follow-up plan.';
cases.rahman.steps[2].options[2]='Notify presumptive TB through CDLENS, communicate findings and pending tests, and confirm follow-up responsibility.';
cases.anita.steps[0].options[1]='Defer rifampicin; assess 6H suitability and coordinate focused advice if the interaction or regimen decision remains complex.';
cases.anita.steps[0].why='Avoid the flagged rifampicin–apixaban combination. Assess 6H as an in-scope alternative, including its own interactions and hepatic risk. Seek NTBSC or anticoagulation advice as required; do not stop anticoagulation unilaterally.';
cases.anita.steps.push(Q('An agreed 6H plan','After medication review and focused advice, Anita chooses 6H. Disease has been excluded; the source is isoniazid-susceptible. She weighs 60 kg. Supplied reference: isoniazid 5 mg/kg daily, maximum 300 mg.','Which prescription fits this agreed plan?',['Isoniazid 300 mg orally daily for six months, with pyridoxine and an agreed monitoring plan','Isoniazid 600 mg orally daily for six months, with monitoring','Isoniazid 300 mg orally daily for four months, with monitoring'],[0],'At 60 kg, 5 mg/kg gives 300 mg daily. 6H lasts six months. Include pyridoxine and review hepatic and neuropathy risks.','A suitable alternative can keep preventive care in general practice.','treatment'));
const notifyItem=challenge.steps.find(q=>q.id==='SUM-09-1');
notifyItem.text='A presumptive diagnosis of pulmonary TB has been made and disease treatment is planned through NTBCC. Culture is pending.';
notifyItem.options[2]='Notify presumptive TB through CDLENS; referral is a separate action.';
notifyItem.why='Presumptive as well as confirmed TB is notified. Do not wait for culture confirmation. The unresolved distinction around investigation-only referrals is not tested here.';
const doseItem=challenge.steps.find(q=>q.id==='SUM-05-2');
doseItem.text='A 75-kg adult has chosen 6H after disease exclusion and a completed suitability assessment. Supplied reference: isoniazid 5 mg/kg daily, maximum 300 mg.';
doseItem.options=['150 mg','375 mg','600 mg','300 mg'];doseItem.why='The weight-based amount exceeds the 300 mg daily maximum. The agreed 6H regimen lasts six months; include pyridoxine and monitoring.';
challenge.steps.find(q=>q.id==='SUM-03-3').options[1]='Coordinate indicated specimen collection through the receiving service when unavailable in the practice';
videos[1].message='Complete clinical assessment and CXR before preventive treatment. Refer for sputum investigation when indicated and unavailable in the practice.';
videos[2].message='Choose between 4R and 6H within GP scope; check drug-specific suitability and seek focused advice or shared care when needed.';
videos[3].next='Explain TB infection and TB disease first; then address infectiousness as a separate question.';
videos[5].message='Use the agreed baseline ALT/AST and risk-based 4–6 weekly testing plan; review symptoms, adherence and new medicines, with access to urgent advice.';
videos[6].message='Keep uncomplicated treatment with the GP. Agree shared-care responsibilities for complexity; MDR contacts require specialist assessment.';
clinicalReviewItems.splice(0,clinicalReviewItems.length,
['Confirmed care model','Adult GP prescribing: 4R and 6H. CXR before treatment. NTBSC advice/shared care for complexity; mandatory specialist assessment for MDR contacts.','Teaching and assessment updated'],
['Hepatic risk and adverse effects','Confirm high-risk criteria, baseline deferral thresholds, mild-rash handling and local implementation of international stopping thresholds.','Monitoring'],
['Notification boundary','CDLENS for presumptive/confirmed disease. Reconcile investigation-only referral wording with CDA suspected-case notification guidance. No contested exemption is scored.','Disease pathway'],
['Completion and interruptions','Confirm dose-count, maximum-duration and interruption rules for 4R and 6H.','Completion'],
['Pyridoxine','Confirm programme dose; supplementation is taught, dose is not scored.','6H prescribing'],
['Contact surveillance','Confirm eligibility, duration and service responsibility for six-monthly CXR surveillance.','Follow-up'],
['Summative certificate','Certificate of completion after approved summative standard; no workplace assessment. Confirm issuer/signatory, pass standard and reassessment form. Issuance remains unimplemented.','Assessment'],
['Expert review','Clinical lead with independent TB/GP and nursing/pharmacy review. Review synthetic CXR anatomy and appearance with a radiologist before diagnostic use.','Governance'],
['Media','Synthetic CXR discussion sheet added; no image-based summative scoring. Record eight approved explainers with captions and transcripts.','Media']
);
foundations=function(){return `<div class="eyebrow">TB FOUNDATIONS</div><h1>Understand the distinction. Apply the evidence.</h1><p class="intro">TB infection and TB disease organise clinical care. Infectiousness is a separate assessment.</p>${naturalGraphic}${testGraphic}${careGraphic}<div class="actions"><a class="btn" href="#lesson/biology">Explore the foundations →</a><a class="btn secondary" href="#lesson/disease">Explore the CXR discussion →</a></div>`;};
reference=function(){return `<div class="eyebrow">CLINICAL REFERENCE</div><h1>The clinical reference shelf.</h1><p class="intro">GP scope: uncomplicated adult TB infection with 4R or 6H. Updated 7 September 2026.</p>${careGraphic}<section class="card"><h2>Singapore guidance and course care model</h2><p>CXR precedes preventive treatment. Obtain baseline ALT/AST under the agreed course model; high-risk patients have 4–6 weekly repeat testing. Clinical follow-up generally occurs at 4–6 weeks and may be extended for adherent patients at low adverse-event risk. Drug-specific contraindications and specialist consultation requirements still apply.</p><p><a href="${refs.sg}" target="_blank" rel="noopener">Singapore TB clinical management guidelines 2024 · pp.170–186 ↗</a></p><p>The full public guideline has been reviewed for these teaching points. Routine baseline testing is the course model; the guideline permits baseline testing. Service destinations and the agreed GP scope are local course instructions.</p></section><section class="card"><h2>Notification</h2><p>Use CDLENS for presumptive and confirmed TB. CDA guidance also specifies suspected cases. The investigation-only referral boundary needs programme clarification; a general exemption is not taught or scored.</p>${sourceLink('cda')} ${sourceLink('notification')}</section><section class="card"><h2>International references</h2><p>CDC supports the adult dose references, test interpretation and the explicitly supplied adverse-effect thresholds. Its monthly clinical-review recommendation is an international alternative. WHO provides specialist preventive-care context; other regimens do not extend this course’s GP prescribing scope.</p>${sourceLink('treatment')} ${sourceLink('overview')} ${sourceLink('who')}</section><section class="card"><h2>Review and assessment</h2><p>The intended award is a certificate of completion after an approved summative assessment. There is no workplace assessment or claim of independently demonstrated clinical competence. Certificate issuance is not active in this educator-review edition.</p><a href="#editorial">Open clinical and educational review points →</a></section>`;};
