import assert from 'node:assert/strict';
import {score,passes,eligible,fresh,validateEvaluation,sanitise} from './rules.mjs';
import {readFileSync} from 'node:fs';
const c=JSON.parse(readFileSync(new URL('./content.json',import.meta.url)));
assert.equal(c.challenge.steps.length,30);
assert.equal(passes(21),true);assert.equal(passes(20.999),false);
assert.equal(passes(NaN),false);
for(const q of c.challenge.steps)assert.equal(score(q,q.answer),1);
assert.equal(score({options:['a','b','c','d'],answer:[0,1],multi:true},[0]),.5);
assert.equal(score({options:['a','b','c','d'],answer:[0,1],multi:true},[0,2]),0);
assert.throws(()=>score({options:['a','b'],answer:[0]},[0,0]));
assert.throws(()=>score({options:['a','b'],answer:[0]},[3]));
assert.equal('answer' in sanitise(c.challenge.steps[0]),false);
const s=fresh();assert.equal(eligible(s,c),false);
s.pre={};s.post={};for(const l of c.lessonData)s.lessons[l.id]=true;
for(const id of c.caseOrder)s.cases[id]=c.cases[id].steps.map(()=>({}));
s.attempts=[{finished:true,score:21}];assert.equal(eligible(s,c),true);
s.attempts[0].score=20.99;assert.equal(eligible(s,c),false);
s.attempts[0].score=21;delete s.lessons[c.lessonData[0].id];assert.equal(eligible(s,c),false);
const input={answers:Object.fromEntries(c.anchorItems.map(q=>[q.id,q.answer])),confidence:Object.fromEntries(c.confidenceAreas.map(([id])=>[id,3]))};
assert.equal(validateEvaluation(input,c).score,10);
input.confidence[c.confidenceAreas[0][0]]=null;assert.equal(validateEvaluation(input,c).confidence[c.confidenceAreas[0][0]],null);
console.log('Passed: threshold, all 30 scoring keys, partial credit, invalid responses, answer redaction, completion gates and midpoint/opt-out confidence.');
